
#ifndef __COMMANDS__
#define __COMMANDS__

#define TAIL_COMMAND						"\r\n"
#define AT_COMMAND							"AT"
#define RESET_COMMAND						"+RESET"
#define VERSION_COMMAND						"+VERSION?"
#define RESTORE_DEFAULTS_COMAMND			"+ORGL"
#define POLL_ADDRESS_COMMAND				"+ADDR?"

#define SET_DEVICE_NAME_COMMAND				"+NAME="
#define GET_DEVICE_NAME_COMMAND				"+NAME?"

#define GET_REMOTE_DEVICE_NAME_COMMAND		"+RNAME?"

#define SET_DEVICE_ROLE_COMMAND				"+ROLE="
#define GET_DEVICE_ROLE_COMAMND				"+ROLE?"

#define SET_DEVICE_TYPE_COMMAND				"+CLASS="
#define GET_DEVICE_TYPE_COMMAND				"+CLASS?"

#define SET_DEVICE_ACCESS_CODE_COMMAND		"+IAC="
#define GET_DEVICE_ACCESS_CODE_COMMAND		"+IAC?"

#define SET_DEVICE_INQUIRY_MODE_COMMAND		"+INQM="
#define GET_DEVICE_INQUIRY_MODE_COMMAND		"+INQM?"

#define SET_PAIRING_PASSWORD_COMMAND		"+PSWD="
#define GET_PAIRING_PASSWORD_COMMAND		"+PSWD?"

#define SET_SERIAL_PORT_COMMAND				"+UART="
#define GET_SERIAL_PORT_COMMAND				"+UART?"

#define SET_CONNECTION_MODE_COMMAND			"+CMODE="
#define GET_CONNECTION_MODE_COMMAND			"+CMODE?"

#define SET_BINDING_ADDRESS_COMMAND			"+BIND="
#define GET_BINDING_ADDRESS_COMMAND			"+BIND?"

#define SET_POLARITY_LED_COMMAND			"+POLAR="
#define GET_POLARITY_LED_COMMAND			"+POLAR?"

#define SET_POI_COMMNAD						"+PIO="
#define SET_MULTIPLE_PIO_COMMAND			"+MPIO="
#define GET_PIO_INPUT_COMMAND				"+MPIO?"

#define SET_INQUIRY_PARAMETERS_COMMAND		"+IPSCAN="
#define GET_INQUIRY_PARAMETERS_COMMAND		"+IPSCAN?"

#define SET_POWER_SAVING_PARAMETERS_COMMAND	"+SNIFF="
#define GET_POWER_SAVING_PARAMETERS_COMMAND "+SNIFF?"

#define SET_ENCRYPTION_COMMAND				"+SENM="
#define GET_ENCRYPTION_COMMAND				"+SENM?"

#define DELETE_DEVICE_ENTRY_FROM_NET_TABLE	"+RMSAD="
#define DELETE_ALL_ENTRIES_FROM_NET_TABLE	"+RMSAD"

#define GET_AUTHENTICATED_DEVICE_COMMAND	"+FSAD="
#define GET_NETWORK_TABLE_LIST_LENGTH		"+ADCN?="

#define GET_MOST_RECENTLY_USED_COMAMND		"+MRAD?"
#define GET_DEVICE_STATE_COMMAND			"+STATE?"

#define INIT_DEVICE_COMMAND					"+INIT"
#define CREATE_NETWORK_MAP_COMMAND			"+INQ"

#define CANCEL_NETWORK_MAP_COMMAND			"+INQC"
#define PAIR_DEVICE_COMMAND					"+PAIR="
#define LINK_DEVICE_COMMAND					"+LINK="
#define DISCONNECT_DEVICE_COMMAND			"+DISC"
#define GO_INTO_ENERGY_SAVING_MODE_COMMAND	"+ENSNIFF="
#define EXIT_ENERGY_SAVING_MODE_COMMAND		"+EXSNIFF="

#define SOFTWARE_VERSION		"1.0-20090818"

enum device_state {
	INIT = "INITIALIZED",
	READY = "READY",
	PAIRABLE = "PAIRABLE",
	PAIRED = "PAIRD",
	NMAP = "INQUIRING",
	CONNECTING = "CONNECTING",
	CONNECTED = "CONNECTED",
	DISCONNECTED = "DISCONNECTED",
	UNKNOWN = "NUKNOW",
	};

#endif