.TH "Included Libraries/USB_Host_Shield_2.0-master/adk.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/adk.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBADK\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBADK_VID\fP   0x18D1"
.br
.ti -1c
.RI "#define \fBADK_PID\fP   0x2D00"
.br
.ti -1c
.RI "#define \fBADB_PID\fP   0x2D01"
.br
.ti -1c
.RI "#define \fBXOOM\fP"
.br
.ti -1c
.RI "#define \fBADK_GETPROTO\fP   51"
.br
.ti -1c
.RI "#define \fBADK_SENDSTR\fP   52"
.br
.ti -1c
.RI "#define \fBADK_ACCSTART\fP   53"
.br
.ti -1c
.RI "#define \fBbmREQ_ADK_GET\fP   USB_SETUP_DEVICE_TO_HOST|USB_SETUP_TYPE_VENDOR|USB_SETUP_RECIPIENT_DEVICE"
.br
.ti -1c
.RI "#define \fBbmREQ_ADK_SEND\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_VENDOR|USB_SETUP_RECIPIENT_DEVICE"
.br
.ti -1c
.RI "#define \fBACCESSORY_STRING_MANUFACTURER\fP   0"
.br
.ti -1c
.RI "#define \fBACCESSORY_STRING_MODEL\fP   1"
.br
.ti -1c
.RI "#define \fBACCESSORY_STRING_DESCRIPTION\fP   2"
.br
.ti -1c
.RI "#define \fBACCESSORY_STRING_VERSION\fP   3"
.br
.ti -1c
.RI "#define \fBACCESSORY_STRING_URI\fP   4"
.br
.ti -1c
.RI "#define \fBACCESSORY_STRING_SERIAL\fP   5"
.br
.ti -1c
.RI "#define \fBADK_MAX_ENDPOINTS\fP   3"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBACCESSORY_STRING_DESCRIPTION\fP   2"
.PP
Definition at line 44 of file adk\&.h\&.
.SS "#define \fBACCESSORY_STRING_MANUFACTURER\fP   0"
.PP
Definition at line 42 of file adk\&.h\&.
.SS "#define \fBACCESSORY_STRING_MODEL\fP   1"
.PP
Definition at line 43 of file adk\&.h\&.
.SS "#define \fBACCESSORY_STRING_SERIAL\fP   5"
.PP
Definition at line 47 of file adk\&.h\&.
.SS "#define \fBACCESSORY_STRING_URI\fP   4"
.PP
Definition at line 46 of file adk\&.h\&.
.SS "#define \fBACCESSORY_STRING_VERSION\fP   3"
.PP
Definition at line 45 of file adk\&.h\&.
.SS "#define \fBADB_PID\fP   0x2D01"
.PP
Definition at line 27 of file adk\&.h\&.
.SS "#define \fBADK_ACCSTART\fP   53"
.PP
Definition at line 37 of file adk\&.h\&.
.SS "#define \fBADK_GETPROTO\fP   51"
.PP
Definition at line 35 of file adk\&.h\&.
.SS "#define \fBADK_MAX_ENDPOINTS\fP   3"
.PP
Definition at line 49 of file adk\&.h\&.
.SS "#define \fBADK_PID\fP   0x2D00"
.PP
Definition at line 26 of file adk\&.h\&.
.SS "#define \fBADK_SENDSTR\fP   52"
.PP
Definition at line 36 of file adk\&.h\&.
.SS "#define \fBADK_VID\fP   0x18D1"
.PP
Definition at line 25 of file adk\&.h\&.
.SS "#define \fBbmREQ_ADK_GET\fP   USB_SETUP_DEVICE_TO_HOST|USB_SETUP_TYPE_VENDOR|USB_SETUP_RECIPIENT_DEVICE"
.PP
Definition at line 39 of file adk\&.h\&.
.SS "#define \fBbmREQ_ADK_SEND\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_VENDOR|USB_SETUP_RECIPIENT_DEVICE"
.PP
Definition at line 40 of file adk\&.h\&.
.SS "#define \fBXOOM\fP"
.PP
Definition at line 29 of file adk\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
