.TH "CommandStatusWrapper" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandStatusWrapper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <masstorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdCSWSignature\fP"
.br
.ti -1c
.RI "uint32_t \fBdCSWTag\fP"
.br
.ti -1c
.RI "uint32_t \fBdCSWDataResidue\fP"
.br
.ti -1c
.RI "uint8_t \fBbCSWStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 436 of file masstorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBCommandStatusWrapper::bCSWStatus\fP"
.PP
Definition at line 440 of file masstorage\&.h\&.
.SS "uint32_t \fBCommandStatusWrapper::dCSWDataResidue\fP"
.PP
Definition at line 439 of file masstorage\&.h\&.
.SS "uint32_t \fBCommandStatusWrapper::dCSWSignature\fP"
.PP
Definition at line 437 of file masstorage\&.h\&.
.SS "uint32_t \fBCommandStatusWrapper::dCSWTag\fP"
.PP
Definition at line 438 of file masstorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
