.TH "FTDI" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTDI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cdcftdi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFTDI\fP (USB *pusb, \fBFTDIAsyncOper\fP *pasync)"
.br
.ti -1c
.RI "uint8_t \fBSetBaudRate\fP (uint32_t baud)"
.br
.ti -1c
.RI "uint8_t \fBSetModemControl\fP (uint16_t control)"
.br
.ti -1c
.RI "uint8_t \fBSetFlowControl\fP (uint8_t protocol, uint8_t xon=0x11, uint8_t xoff=0x13)"
.br
.ti -1c
.RI "uint8_t \fBSetData\fP (uint16_t databm)"
.br
.ti -1c
.RI "uint8_t \fBRcvData\fP (uint16_t *bytes_rcvd, uint8_t *dataptr)"
.br
.ti -1c
.RI "uint8_t \fBSndData\fP (uint16_t nbytes, uint8_t *dataptr)"
.br
.ti -1c
.RI "virtual uint8_t \fBInit\fP (uint8_t parent, uint8_t port, bool lowspeed)"
.br
.ti -1c
.RI "virtual uint8_t \fBRelease\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBPoll\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBGetAddress\fP ()"
.br
.ti -1c
.RI "virtual void \fBEndpointXtract\fP (uint8_t conf, uint8_t iface, uint8_t alt, uint8_t proto, const USB_ENDPOINT_DESCRIPTOR *ep)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file cdcftdi\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFTDI::FTDI\fP (USB *pusb, \fBFTDIAsyncOper\fP *pasync)"
.PP
Definition at line 23 of file cdcftdi\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBFTDI::EndpointXtract\fP (uint8_tconf, uint8_tiface, uint8_talt, uint8_tproto, const USB_ENDPOINT_DESCRIPTOR *ep)\fC [virtual]\fP"
.PP
Definition at line 215 of file cdcftdi\&.cpp\&.
.SS "virtual uint8_t \fBFTDI::GetAddress\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 125 of file cdcftdi\&.h\&.
.SS "uint8_t \fBFTDI::Init\fP (uint8_tparent, uint8_tport, boollowspeed)\fC [virtual]\fP"
.PP
Definition at line 41 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::Poll\fP ()\fC [virtual]\fP"
.PP
Definition at line 252 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::RcvData\fP (uint16_t *bytes_rcvd, uint8_t *dataptr)"
.PP
Definition at line 316 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::Release\fP ()\fC [virtual]\fP"
.PP
Definition at line 242 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::SetBaudRate\fP (uint32_tbaud)"
.PP
Definition at line 267 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::SetData\fP (uint16_tdatabm)"
.PP
Definition at line 312 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::SetFlowControl\fP (uint8_tprotocol, uint8_txon = \fC0x11\fP, uint8_txoff = \fC0x13\fP)"
.PP
Definition at line 308 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::SetModemControl\fP (uint16_tcontrol)"
.PP
Definition at line 304 of file cdcftdi\&.cpp\&.
.SS "uint8_t \fBFTDI::SndData\fP (uint16_tnbytes, uint8_t *dataptr)"
.PP
Definition at line 320 of file cdcftdi\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
