.TH "MainItemIOFeature" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainItemIOFeature \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hid\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbmIsConstantOrData\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmIsArrayOrVariable\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmIsRelativeOrAbsolute\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmIsWrapOrNoWrap\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmIsNonLonearOrLinear\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmIsNoPreferedOrPrefered\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmIsNullOrNoNull\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmIsVolatileOrNonVolatile\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file hid\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBMainItemIOFeature::bmIsArrayOrVariable\fP"
.PP
Definition at line 127 of file hid\&.h\&.
.SS "uint8_t \fBMainItemIOFeature::bmIsConstantOrData\fP"
.PP
Definition at line 126 of file hid\&.h\&.
.SS "uint8_t \fBMainItemIOFeature::bmIsNonLonearOrLinear\fP"
.PP
Definition at line 130 of file hid\&.h\&.
.SS "uint8_t \fBMainItemIOFeature::bmIsNoPreferedOrPrefered\fP"
.PP
Definition at line 131 of file hid\&.h\&.
.SS "uint8_t \fBMainItemIOFeature::bmIsNullOrNoNull\fP"
.PP
Definition at line 132 of file hid\&.h\&.
.SS "uint8_t \fBMainItemIOFeature::bmIsRelativeOrAbsolute\fP"
.PP
Definition at line 128 of file hid\&.h\&.
.SS "uint8_t \fBMainItemIOFeature::bmIsVolatileOrNonVolatile\fP"
.PP
Definition at line 133 of file hid\&.h\&.
.SS "uint8_t \fBMainItemIOFeature::bmIsWrapOrNoWrap\fP"
.PP
Definition at line 129 of file hid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
