.TH "Included Libraries/SoftwareSerial.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/SoftwareSerial.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include <avr/pgmspace\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br
\fC#include <SoftwareSerial\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_DELAY_TABLE\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_DEBUG\fP   0"
.br
.ti -1c
.RI "#define \fB_DEBUG_PIN1\fP   11"
.br
.ti -1c
.RI "#define \fB_DEBUG_PIN2\fP   13"
.br
.ti -1c
.RI "#define \fBF_CPU\fP   16000000"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_DELAY_TABLE\fP \fBDELAY_TABLE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDebugPulse\fP (uint8_t pin, uint8_t count)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBXMIT_START_ADJUSTMENT\fP = 5"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fB_DEBUG\fP   0"
.PP
Definition at line 35 of file SoftwareSerial\&.cpp\&.
.SS "#define \fB_DEBUG_PIN1\fP   11"
.PP
Definition at line 36 of file SoftwareSerial\&.cpp\&.
.SS "#define \fB_DEBUG_PIN2\fP   13"
.PP
Definition at line 37 of file SoftwareSerial\&.cpp\&.
.SS "#define \fBF_CPU\fP   16000000"
.PP
Definition at line 39 of file SoftwareSerial\&.cpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_DELAY_TABLE\fP  \fBDELAY_TABLE\fP"
.SH "Function Documentation"
.PP 
.SS "void \fBDebugPulse\fP (uint8_tpin, uint8_tcount)\fC [inline]\fP"
.PP
Definition at line 148 of file SoftwareSerial\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const int \fBXMIT_START_ADJUSTMENT\fP = 5"
.PP
Definition at line 80 of file SoftwareSerial\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
