.TH "TimerOne" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerOne \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TimerOne\&.h>\fP
.PP
Inherited by \fBGHID_System_Abstration::GHID_Timer_One\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (long microseconds=1000000)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBrestart\fP ()"
.br
.ti -1c
.RI "void \fBresume\fP ()"
.br
.ti -1c
.RI "unsigned long \fBread\fP ()"
.br
.ti -1c
.RI "void \fBpwm\fP (char pin, int duty, long microseconds=-1)"
.br
.ti -1c
.RI "void \fBdisablePwm\fP (char pin)"
.br
.ti -1c
.RI "void \fBattachInterrupt\fP (void(*isr)(), long microseconds=-1)"
.br
.ti -1c
.RI "void \fBdetachInterrupt\fP ()"
.br
.ti -1c
.RI "void \fBsetPeriod\fP (long microseconds)"
.br
.ti -1c
.RI "void \fBsetPwmDuty\fP (char pin, int duty)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBpwmPeriod\fP"
.br
.ti -1c
.RI "unsigned char \fBclockSelectBits\fP"
.br
.ti -1c
.RI "char \fBoldSREG\fP"
.br
.ti -1c
.RI "void(* \fBisrCallback\fP )()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file TimerOne\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBTimerOne::attachInterrupt\fP (void(*)()isr, longmicroseconds = \fC-1\fP)"
.PP
Definition at line 113 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::detachInterrupt\fP ()"
.PP
Definition at line 123 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::disablePwm\fP (charpin)"
.PP
Definition at line 107 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::initialize\fP (longmicroseconds = \fC1000000\fP)"
.PP
Definition at line 49 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::pwm\fP (charpin, intduty, longmicroseconds = \fC-1\fP)"
.PP
Definition at line 91 of file TimerOne\&.cpp\&.
.SS "unsigned long \fBTimerOne::read\fP (void)"
.PP
Definition at line 167 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::restart\fP ()"
.PP
Definition at line 134 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::resume\fP ()"
.PP
Definition at line 129 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::setPeriod\fP (longmicroseconds)"
.PP
Definition at line 57 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::setPwmDuty\fP (charpin, intduty)"
.PP
Definition at line 77 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::start\fP ()"
.PP
Definition at line 139 of file TimerOne\&.cpp\&.
.SS "void \fBTimerOne::stop\fP ()"
.PP
Definition at line 162 of file TimerOne\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char \fBTimerOne::clockSelectBits\fP"
.PP
Definition at line 50 of file TimerOne\&.h\&.
.SS "void(* \fBTimerOne::isrCallback\fP)()"
.PP
Definition at line 66 of file TimerOne\&.h\&.
.SS "char \fBTimerOne::oldSREG\fP"
.PP
Definition at line 51 of file TimerOne\&.h\&.
.SS "unsigned int \fBTimerOne::pwmPeriod\fP"
.PP
Definition at line 49 of file TimerOne\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
