.TH "Included Libraries/USB_Host_Shield_2.0-master/XBOXRECV.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/XBOXRECV.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br
\fC#include 'xboxEnums\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXBOXRECV\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEP_MAXPKTSIZE\fP   32"
.br
.ti -1c
.RI "#define \fBEP_INTERRUPT\fP   0x03"
.br
.ti -1c
.RI "#define \fBXBOX_CONTROL_PIPE\fP   0"
.br
.ti -1c
.RI "#define \fBXBOX_INPUT_PIPE_1\fP   1"
.br
.ti -1c
.RI "#define \fBXBOX_OUTPUT_PIPE_1\fP   2"
.br
.ti -1c
.RI "#define \fBXBOX_INPUT_PIPE_2\fP   3"
.br
.ti -1c
.RI "#define \fBXBOX_OUTPUT_PIPE_2\fP   4"
.br
.ti -1c
.RI "#define \fBXBOX_INPUT_PIPE_3\fP   5"
.br
.ti -1c
.RI "#define \fBXBOX_OUTPUT_PIPE_3\fP   6"
.br
.ti -1c
.RI "#define \fBXBOX_INPUT_PIPE_4\fP   7"
.br
.ti -1c
.RI "#define \fBXBOX_OUTPUT_PIPE_4\fP   8"
.br
.ti -1c
.RI "#define \fBXBOX_VID\fP   0x045E"
.br
.ti -1c
.RI "#define \fBMADCATZ_VID\fP   0x1BAD"
.br
.ti -1c
.RI "#define \fBJOYTECH_VID\fP   0x162E"
.br
.ti -1c
.RI "#define \fBXBOX_WIRELESS_RECEIVER_PID\fP   0x0719"
.br
.ti -1c
.RI "#define \fBXBOX_WIRELESS_RECEIVER_THIRD_PARTY_PID\fP   0x0291"
.br
.ti -1c
.RI "#define \fBXBOX_MAX_ENDPOINTS\fP   9"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBEP_INTERRUPT\fP   0x03"
.PP
Definition at line 30 of file XBOXRECV\&.h\&.
.SS "#define \fBEP_MAXPKTSIZE\fP   32"
.PP
Definition at line 27 of file XBOXRECV\&.h\&.
.SS "#define \fBJOYTECH_VID\fP   0x162E"
.PP
Definition at line 46 of file XBOXRECV\&.h\&.
.SS "#define \fBMADCATZ_VID\fP   0x1BAD"
.PP
Definition at line 45 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_CONTROL_PIPE\fP   0"
.PP
Definition at line 33 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_INPUT_PIPE_1\fP   1"
.PP
Definition at line 34 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_INPUT_PIPE_2\fP   3"
.PP
Definition at line 36 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_INPUT_PIPE_3\fP   5"
.PP
Definition at line 38 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_INPUT_PIPE_4\fP   7"
.PP
Definition at line 40 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_MAX_ENDPOINTS\fP   9"
.PP
Definition at line 51 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_OUTPUT_PIPE_1\fP   2"
.PP
Definition at line 35 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_OUTPUT_PIPE_2\fP   4"
.PP
Definition at line 37 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_OUTPUT_PIPE_3\fP   6"
.PP
Definition at line 39 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_OUTPUT_PIPE_4\fP   8"
.PP
Definition at line 41 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_VID\fP   0x045E"
.PP
Definition at line 44 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_WIRELESS_RECEIVER_PID\fP   0x0719"
.PP
Definition at line 48 of file XBOXRECV\&.h\&.
.SS "#define \fBXBOX_WIRELESS_RECEIVER_THIRD_PARTY_PID\fP   0x0291"
.PP
Definition at line 49 of file XBOXRECV\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
