.TH "_DELAY_TABLE" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DELAY_TABLE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBbaud\fP"
.br
.ti -1c
.RI "unsigned short \fBrx_delay_centering\fP"
.br
.ti -1c
.RI "unsigned short \fBrx_delay_intrabit\fP"
.br
.ti -1c
.RI "unsigned short \fBrx_delay_stopbit\fP"
.br
.ti -1c
.RI "unsigned short \fBtx_delay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file SoftwareSerial\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "long \fB_DELAY_TABLE::baud\fP"
.PP
Definition at line 53 of file SoftwareSerial\&.cpp\&.
.SS "unsigned short \fB_DELAY_TABLE::rx_delay_centering\fP"
.PP
Definition at line 54 of file SoftwareSerial\&.cpp\&.
.SS "unsigned short \fB_DELAY_TABLE::rx_delay_intrabit\fP"
.PP
Definition at line 55 of file SoftwareSerial\&.cpp\&.
.SS "unsigned short \fB_DELAY_TABLE::rx_delay_stopbit\fP"
.PP
Definition at line 56 of file SoftwareSerial\&.cpp\&.
.SS "unsigned short \fB_DELAY_TABLE::tx_delay\fP"
.PP
Definition at line 57 of file SoftwareSerial\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
