.TH "ADK" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADK \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adk\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBADK\fP (USB *\fBpUsb\fP, const char *manufacturer, const char *model, const char *description, const char *version, const char *uri, const char *serial)"
.br
.ti -1c
.RI "uint8_t \fBRcvData\fP (uint16_t *nbytesptr, uint8_t *dataptr)"
.br
.ti -1c
.RI "uint8_t \fBSndData\fP (uint16_t nbytes, uint8_t *dataptr)"
.br
.ti -1c
.RI "virtual uint8_t \fBConfigureDevice\fP (uint8_t parent, uint8_t port, bool lowspeed)"
.br
.ti -1c
.RI "virtual uint8_t \fBInit\fP (uint8_t parent, uint8_t port, bool lowspeed)"
.br
.ti -1c
.RI "virtual uint8_t \fBRelease\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBPoll\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBGetAddress\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisReady\fP ()"
.br
.ti -1c
.RI "virtual boolean \fBVIDPIDOK\fP (uint16_t vid, uint16_t pid)"
.br
.ti -1c
.RI "virtual void \fBEndpointXtract\fP (uint8_t conf, uint8_t iface, uint8_t alt, uint8_t proto, const USB_ENDPOINT_DESCRIPTOR *ep)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBPrintEndpointDescriptor\fP (const USB_ENDPOINT_DESCRIPTOR *ep_ptr)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "USB * \fBpUsb\fP"
.br
.ti -1c
.RI "uint8_t \fBbAddress\fP"
.br
.ti -1c
.RI "uint8_t \fBbConfNum\fP"
.br
.ti -1c
.RI "uint8_t \fBbNumEP\fP"
.br
.ti -1c
.RI "bool \fBready\fP"
.br
.ti -1c
.RI "EpInfo \fBepInfo\fP [\fBADK_MAX_ENDPOINTS\fP]"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const uint8_t \fBepDataInIndex\fP = 1"
.br
.ti -1c
.RI "static const uint8_t \fBepDataOutIndex\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file adk\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBADK::ADK\fP (USB *pUsb, const char *manufacturer, const char *model, const char *description, const char *version, const char *uri, const char *serial)"
.PP
Definition at line 25 of file adk\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint8_t \fBADK::ConfigureDevice\fP (uint8_tparent, uint8_tport, boollowspeed)\fC [virtual]\fP"
.PP
Definition at line 58 of file adk\&.cpp\&.
.SS "void \fBADK::EndpointXtract\fP (uint8_tconf, uint8_tiface, uint8_talt, uint8_tproto, const USB_ENDPOINT_DESCRIPTOR *ep)\fC [virtual]\fP"
.PP
Definition at line 311 of file adk\&.cpp\&.
.SS "virtual uint8_t \fBADK::GetAddress\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 107 of file adk\&.h\&.
.SS "uint8_t \fBADK::Init\fP (uint8_tparent, uint8_tport, boollowspeed)\fC [virtual]\fP"
.PP
Definition at line 63 of file adk\&.cpp\&.
.SS "virtual bool \fBADK::isReady\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 111 of file adk\&.h\&.
.SS "virtual uint8_t \fBADK::Poll\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 103 of file adk\&.h\&.
.SS "void \fBADK::PrintEndpointDescriptor\fP (const USB_ENDPOINT_DESCRIPTOR *ep_ptr)\fC [protected]\fP"
.PP
Definition at line 356 of file adk\&.cpp\&.
.SS "uint8_t \fBADK::RcvData\fP (uint16_t *nbytesptr, uint8_t *dataptr)"
.PP
Definition at line 346 of file adk\&.cpp\&.
.SS "uint8_t \fBADK::Release\fP ()\fC [virtual]\fP"
.PP
Definition at line 336 of file adk\&.cpp\&.
.SS "uint8_t \fBADK::SndData\fP (uint16_tnbytes, uint8_t *dataptr)"
.PP
Definition at line 352 of file adk\&.cpp\&.
.SS "virtual boolean \fBADK::VIDPIDOK\fP (uint16_tvid, uint16_tpid)\fC [inline, virtual]\fP"
.PP
Definition at line 115 of file adk\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBADK::bAddress\fP\fC [protected]\fP"
.PP
Definition at line 74 of file adk\&.h\&.
.SS "uint8_t \fBADK::bConfNum\fP\fC [protected]\fP"
.PP
Definition at line 75 of file adk\&.h\&.
.SS "uint8_t \fBADK::bNumEP\fP\fC [protected]\fP"
.PP
Definition at line 77 of file adk\&.h\&.
.SS "const uint8_t \fBADK::epDataInIndex\fP = 1\fC [static, protected]\fP"
.PP
Definition at line 69 of file adk\&.h\&.
.SS "const uint8_t \fBADK::epDataOutIndex\fP = 2\fC [static, protected]\fP"
.PP
Definition at line 70 of file adk\&.h\&.
.SS "EpInfo \fBADK::epInfo\fP[\fBADK_MAX_ENDPOINTS\fP]\fC [protected]\fP"
.PP
Definition at line 81 of file adk\&.h\&.
.SS "USB* \fBADK::pUsb\fP\fC [protected]\fP"
.PP
Definition at line 73 of file adk\&.h\&.
.SS "bool \fBADK::ready\fP\fC [protected]\fP"
.PP
Definition at line 78 of file adk\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
