.TH "buffer_struct_t" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buffer_struct_t \- 
.PP
Buffer structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GHID_Dallas_1_Wire\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBlength\fP"
.br
.ti -1c
.RI "byte \fBbuffer\fP [\fBMAX_BUFFER\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Buffer structure\&. 
.PP
Definition at line 17 of file GHID_Dallas_1_Wire\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "byte \fBbuffer_struct_t::buffer\fP"
.PP
Definition at line 20 of file GHID_Dallas_1_Wire\&.h\&.
.SS "byte \fBbuffer_struct_t::length\fP"
.PP
Definition at line 19 of file GHID_Dallas_1_Wire\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
