.TH "Included Libraries/USB_Host_Shield_2.0-master/controllerEnums.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/controllerEnums.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLEDEnum\fP { \fBOFF\fP =  0, \fBLED1\fP =  1, \fBLED2\fP =  2, \fBLED3\fP =  3, \fBLED4\fP =  4, \fBLED5\fP =  5, \fBLED6\fP =  6, \fBLED7\fP =  7, \fBLED8\fP =  8, \fBLED9\fP =  9, \fBLED10\fP =  10, \fBALL\fP =  5 }"
.br
.ti -1c
.RI "enum \fBColorsEnum\fP { \fBRed\fP =  0xFF0000, \fBGreen\fP =  0xFF00, \fBBlue\fP =  0xFF, \fBYellow\fP =  0xFFEB04, \fBLightblue\fP =  0xFFFF, \fBPurble\fP =  0xFF00FF, \fBWhite\fP =  0xFFFFFF, \fBOff\fP =  0x00 }"
.br
.ti -1c
.RI "enum \fBRumbleEnum\fP { \fBRumbleHigh\fP =  0x10, \fBRumbleLow\fP =  0x20 }"
.br
.ti -1c
.RI "enum \fBButtonEnum\fP { \fBUP\fP =  0, \fBRIGHT\fP =  1, \fBDOWN\fP =  2, \fBLEFT\fP =  3, \fBPLUS\fP =  5, \fBTWO\fP =  6, \fBONE\fP =  7, \fBMINUS\fP =  8, \fBHOME\fP =  9, \fBZ\fP =  10, \fBC\fP =  11, \fBB\fP =  12, \fBA\fP =  13, \fBL\fP =  16, \fBR\fP =  17, \fBZL\fP =  18, \fBZR\fP =  19, \fBSELECT\fP =  4, \fBSTART\fP =  5, \fBL3\fP =  6, \fBR3\fP =  7, \fBL2\fP =  8, \fBR2\fP =  9, \fBL1\fP =  10, \fBR1\fP =  11, \fBTRIANGLE\fP =  12, \fBCIRCLE\fP =  13, \fBCROSS\fP =  14, \fBSQUARE\fP =  15, \fBPS\fP =  16, \fBMOVE\fP =  17, \fBT\fP =  18, \fBSHARE\fP =  4, \fBOPTIONS\fP =  5, \fBTOUCHPAD\fP =  17, \fBBACK\fP =  4, \fBX\fP =  14, \fBY\fP =  15, \fBXBOX\fP =  16, \fBSYNC\fP =  17, \fBBLACK\fP =  8, \fBWHITE\fP =  9 }"
.br
.ti -1c
.RI "enum \fBAnalogHatEnum\fP { \fBLeftHatX\fP =  0, \fBLeftHatY\fP =  1, \fBRightHatX\fP =  2, \fBRightHatY\fP =  3 }"
.br
.ti -1c
.RI "enum \fBSensorEnum\fP { \fBaX\fP =  50, \fBaY\fP =  52, \fBaZ\fP =  54, \fBgZ\fP =  56, \fBgX\fP, \fBgY\fP, \fBaXmove\fP =  28, \fBaZmove\fP =  30, \fBaYmove\fP =  32, \fBgXmove\fP =  40, \fBgZmove\fP =  42, \fBgYmove\fP =  44, \fBtempMove\fP =  46, \fBmXmove\fP =  47, \fBmZmove\fP =  49, \fBmYmove\fP =  50 }"
.br
.ti -1c
.RI "enum \fBAngleEnum\fP { \fBPitch\fP =  0x01, \fBRoll\fP =  0x02 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAnalogHatEnum\fP"Joysticks on the PS3 and Xbox controllers\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fILeftHatX \fP\fP
Left joystick x-axis 
.TP
\fB\fILeftHatY \fP\fP
Left joystick y-axis 
.TP
\fB\fIRightHatX \fP\fP
Right joystick x-axis 
.TP
\fB\fIRightHatY \fP\fP
Right joystick y-axis 
.PP
Definition at line 143 of file controllerEnums\&.h\&.
.SS "enum \fBAngleEnum\fP"Used to get the angle calculated using the PS3 controller and PS4 controller\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIPitch \fP\fP
.TP
\fB\fIRoll \fP\fP

.PP
Definition at line 191 of file controllerEnums\&.h\&.
.SS "enum \fBButtonEnum\fP"This enum is used to read all the different buttons on the different controllers 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIUP \fP\fP
These buttons are available on all the the controllers 
.TP
\fB\fIRIGHT \fP\fP
.TP
\fB\fIDOWN \fP\fP
.TP
\fB\fILEFT \fP\fP
.TP
\fB\fIPLUS \fP\fP
Wii buttons 
.TP
\fB\fITWO \fP\fP
.TP
\fB\fIONE \fP\fP
.TP
\fB\fIMINUS \fP\fP
.TP
\fB\fIHOME \fP\fP
.TP
\fB\fIZ \fP\fP
.TP
\fB\fIC \fP\fP
.TP
\fB\fIB \fP\fP
.TP
\fB\fIA \fP\fP
.TP
\fB\fIL \fP\fP
These are only available on the Wii U Pro Controller 
.TP
\fB\fIR \fP\fP
.TP
\fB\fIZL \fP\fP
.TP
\fB\fIZR \fP\fP
.TP
\fB\fISELECT \fP\fP
PS3 controllers buttons 
.TP
\fB\fISTART \fP\fP
.TP
\fB\fIL3 \fP\fP
.TP
\fB\fIR3 \fP\fP
.TP
\fB\fIL2 \fP\fP
.TP
\fB\fIR2 \fP\fP
.TP
\fB\fIL1 \fP\fP
.TP
\fB\fIR1 \fP\fP
.TP
\fB\fITRIANGLE \fP\fP
.TP
\fB\fICIRCLE \fP\fP
.TP
\fB\fICROSS \fP\fP
.TP
\fB\fISQUARE \fP\fP
.TP
\fB\fIPS \fP\fP
.TP
\fB\fIMOVE \fP\fP
.TP
\fB\fIT \fP\fP
.TP
\fB\fISHARE \fP\fP
PS4 controllers buttons - SHARE and OPTIONS are present instead of SELECT and START 
.TP
\fB\fIOPTIONS \fP\fP
.TP
\fB\fITOUCHPAD \fP\fP
.TP
\fB\fIBACK \fP\fP
Xbox buttons 
.TP
\fB\fIX \fP\fP
.TP
\fB\fIY \fP\fP
.TP
\fB\fIXBOX \fP\fP
.TP
\fB\fISYNC \fP\fP
.TP
\fB\fIBLACK \fP\fP
.TP
\fB\fIWHITE \fP\fP

.PP
Definition at line 72 of file controllerEnums\&.h\&.
.SS "enum \fBColorsEnum\fP"Used to set the colors of the Move and PS4 controller\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIRed \fP\fP
r = 255, g = 0, b = 0 
.TP
\fB\fIGreen \fP\fP
r = 0, g = 255, b = 0 
.TP
\fB\fIBlue \fP\fP
r = 0, g = 0, b = 255 
.TP
\fB\fIYellow \fP\fP
r = 255, g = 235, b = 4 
.TP
\fB\fILightblue \fP\fP
r = 0, g = 255, b = 255 
.TP
\fB\fIPurble \fP\fP
r = 255, g = 0, b = 255 
.TP
\fB\fIWhite \fP\fP
r = 255, g = 255, b = 255 
.TP
\fB\fIOff \fP\fP
r = 0, g = 0, b = 0 
.PP
Definition at line 45 of file controllerEnums\&.h\&.
.SS "enum \fBLEDEnum\fP"This header file is used to store different enums for the controllers, This is necessary so all the different libraries can be used at once\&. Enum used to turn on the LEDs on the different controllers\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIOFF \fP\fP
.TP
\fB\fILED1 \fP\fP
.TP
\fB\fILED2 \fP\fP
.TP
\fB\fILED3 \fP\fP
.TP
\fB\fILED4 \fP\fP
.TP
\fB\fILED5 \fP\fP
.TP
\fB\fILED6 \fP\fP
.TP
\fB\fILED7 \fP\fP
.TP
\fB\fILED8 \fP\fP
.TP
\fB\fILED9 \fP\fP
.TP
\fB\fILED10 \fP\fP
.TP
\fB\fIALL \fP\fP
Used to blink all LEDs on the Xbox controller 
.PP
Definition at line 27 of file controllerEnums\&.h\&.
.SS "enum \fBRumbleEnum\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIRumbleHigh \fP\fP
.TP
\fB\fIRumbleLow \fP\fP

.PP
Definition at line 66 of file controllerEnums\&.h\&.
.SS "enum \fBSensorEnum\fP"Sensors inside the Sixaxis Dualshock 3, Move controller and PS4 controller\&. \fBNote:\fP that the location is shifted 9 when it's connected via USB on the PS3 controller\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIaX \fP\fP
Accelerometer values 
.TP
\fB\fIaY \fP\fP
.TP
\fB\fIaZ \fP\fP
.TP
\fB\fIgZ \fP\fP
Gyro z-axis 
.TP
\fB\fIgX \fP\fP
.TP
\fB\fIgY \fP\fP
.TP
\fB\fIaXmove \fP\fP
Accelerometer x-axis 
.TP
\fB\fIaZmove \fP\fP
Accelerometer z-axis 
.TP
\fB\fIaYmove \fP\fP
Accelerometer y-axis 
.TP
\fB\fIgXmove \fP\fP
Gyro x-axis 
.TP
\fB\fIgZmove \fP\fP
Gyro z-axis 
.TP
\fB\fIgYmove \fP\fP
Gyro y-axis 
.TP
\fB\fItempMove \fP\fP
Temperature sensor 
.TP
\fB\fImXmove \fP\fP
Magnetometer x-axis 
.TP
\fB\fImZmove \fP\fP
Magnetometer z-axis 
.TP
\fB\fImYmove \fP\fP
Magnetometer y-axis 
.PP
Definition at line 158 of file controllerEnums\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
