.TH "GHID_System_Abstration::GHID_Timer_Three" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID_System_Abstration::GHID_Timer_Three \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GHID_System_Abstration\&.h>\fP
.PP
Inherits \fBTimerThree\fP\&.
.SH "Detailed Description"
.PP 
This class extends the \fBTimerThree\fP class, and gives access to the class contents in this subclass\&.
.PP
\fBSee also:\fP
.RS 4
\fBTimerThree\&.h\fP 
.RE
.PP

.PP
Definition at line 83 of file GHID_System_Abstration\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
