.TH "GHID API/GHID_Analog_Port.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID API/GHID_Analog_Port.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnalog_Port\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_ANALOG_PORTS\fP   15"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMAX_ANALOG_PORTS\fP   15"
.PP
Definition at line 13 of file GHID_Analog_Port\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
