.TH "Included Libraries/USB_Host_Shield_2.0-master/hidboot.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/hidboot.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'hidboot\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t 
.br
KeyboardReportParser::numKeys[10] \fBPROGMEM\fP = {'!', '@', '#', '$', '%', '^', '&', '*', '(', ')'}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t KeyboardReportParser::padKeys [5] \fBPROGMEM\fP = {'!', '@', '#', '$', '%', '^', '&', '*', '(', ')'}"
.PP
Definition at line 181 of file hidboot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
