.TH "Included Libraries/USB_Host_Shield_2.0-master/hiduniversal.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/hiduniversal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'hid\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHIDUniversal\fP"
.br
.ti -1c
.RI "struct \fBHIDUniversal::ReportParser\fP"
.br
.ti -1c
.RI "struct \fBHIDUniversal::HIDInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
