.TH "Included Libraries/OneWire.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/OneWire.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOneWire\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBARDUINO\fP   200"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBARDUINO\fP   200"
.PP
Definition at line 6 of file OneWire\&.h\&.
.SS "#define \fBFALSE\fP   0"
.PP
Definition at line 50 of file OneWire\&.h\&.
.SS "#define \fBTRUE\fP   1"
.PP
Definition at line 51 of file OneWire\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
