.TH "Included Libraries/USB_Host_Shield_2.0-master/PS3Enums.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/PS3Enums.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'controllerEnums\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPS3_REPORT_BUFFER_SIZE\fP   48"
.br
.ti -1c
.RI "#define \fBMOVE_REPORT_BUFFER_SIZE\fP   7"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStatusEnum\fP { \fBPlugged\fP =  (38 << 8) | 0x02, \fBUnplugged\fP =  (38 << 8) | 0x03, \fBCharging\fP =  (39 << 8) | 0xEE, \fBNotCharging\fP =  (39 << 8) | 0xF1, \fBShutdown\fP =  (39 << 8) | 0x01, \fBDying\fP =  (39 << 8) | 0x02, \fBLow\fP =  (39 << 8) | 0x03, \fBHigh\fP =  (39 << 8) | 0x04, \fBFull\fP =  (39 << 8) | 0x05, \fBMoveCharging\fP =  (21 << 8) | 0xEE, \fBMoveNotCharging\fP =  (21 << 8) | 0xF1, \fBMoveShutdown\fP =  (21 << 8) | 0x01, \fBMoveDying\fP =  (21 << 8) | 0x02, \fBMoveLow\fP =  (21 << 8) | 0x03, \fBMoveHigh\fP =  (21 << 8) | 0x04, \fBMoveFull\fP =  (21 << 8) | 0x05, \fBCableRumble\fP =  (40 << 8) | 0x10, \fBCable\fP =  (40 << 8) | 0x12, \fBBluetoothRumble\fP =  (40 << 8) | 0x14, \fBBluetooth\fP =  (40 << 8) | 0x16 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t 
.br
PS3_REPORT_BUFFER[\fBPS3_REPORT_BUFFER_SIZE\fP] \fBPROGMEM\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMOVE_REPORT_BUFFER_SIZE\fP   7"Size of the output report buffer for the Move Controller 
.PP
Definition at line 40 of file PS3Enums\&.h\&.
.SS "#define \fBPS3_REPORT_BUFFER_SIZE\fP   48"Size of the output report buffer for the Dualshock and Navigation controllers 
.PP
Definition at line 24 of file PS3Enums\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBStatusEnum\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIPlugged \fP\fP
.TP
\fB\fIUnplugged \fP\fP
.TP
\fB\fICharging \fP\fP
.TP
\fB\fINotCharging \fP\fP
.TP
\fB\fIShutdown \fP\fP
.TP
\fB\fIDying \fP\fP
.TP
\fB\fILow \fP\fP
.TP
\fB\fIHigh \fP\fP
.TP
\fB\fIFull \fP\fP
.TP
\fB\fIMoveCharging \fP\fP
.TP
\fB\fIMoveNotCharging \fP\fP
.TP
\fB\fIMoveShutdown \fP\fP
.TP
\fB\fIMoveDying \fP\fP
.TP
\fB\fIMoveLow \fP\fP
.TP
\fB\fIMoveHigh \fP\fP
.TP
\fB\fIMoveFull \fP\fP
.TP
\fB\fICableRumble \fP\fP
.TP
\fB\fICable \fP\fP
.TP
\fB\fIBluetoothRumble \fP\fP
.TP
\fB\fIBluetooth \fP\fP

.PP
Definition at line 113 of file PS3Enums\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const uint8_t PS3_ANALOG_BUTTONS [] \fBPROGMEM\fP"\fBInitial value:\fP
.PP
.nf
 {
        0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00,
        0xff, 0x27, 0x10, 0x00, 0x32,
        0xff, 0x27, 0x10, 0x00, 0x32,
        0xff, 0x27, 0x10, 0x00, 0x32,
        0xff, 0x27, 0x10, 0x00, 0x32,
        0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
.fi
Report buffer for all PS3 commands
.PP
Used to set the LEDs on the controllers
.PP
Buttons on the controllers\&. \fBNote:\fP that the location is shifted 9 when it's connected via USB\&.
.PP
Analog buttons on the controllers\&. \fBNote:\fP that the location is shifted 9 when it's connected via USB\&. 
.PP
Definition at line 27 of file PS3Enums\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
