.TH "SPIClass" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPIClass \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SPI\&.h>\fP
.PP
Inherited by \fBGHID_SPI\fP\fC [private]\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static byte \fBtransfer\fP (byte _data)"
.br
.ti -1c
.RI "static void \fBattachInterrupt\fP ()"
.br
.ti -1c
.RI "static void \fBdetachInterrupt\fP ()"
.br
.ti -1c
.RI "static void \fBbegin\fP ()"
.br
.ti -1c
.RI "static void \fBend\fP ()"
.br
.ti -1c
.RI "static void \fBsetBitOrder\fP (uint8_t)"
.br
.ti -1c
.RI "static void \fBsetDataMode\fP (uint8_t)"
.br
.ti -1c
.RI "static void \fBsetClockDivider\fP (uint8_t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file SPI\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBSPIClass::attachInterrupt\fP ()\fC [inline, static]\fP"
.PP
Definition at line 62 of file SPI\&.h\&.
.SS "void \fBSPIClass::begin\fP ()\fC [static]\fP"
.PP
Definition at line 16 of file SPI\&.cpp\&.
.SS "void \fBSPIClass::detachInterrupt\fP ()\fC [inline, static]\fP"
.PP
Definition at line 66 of file SPI\&.h\&.
.SS "void \fBSPIClass::end\fP ()\fC [static]\fP"
.PP
Definition at line 43 of file SPI\&.cpp\&.
.SS "void \fBSPIClass::setBitOrder\fP (uint8_tbitOrder)\fC [static]\fP"
.PP
Definition at line 47 of file SPI\&.cpp\&.
.SS "void \fBSPIClass::setClockDivider\fP (uint8_trate)\fC [static]\fP"
.PP
Definition at line 61 of file SPI\&.cpp\&.
.SS "void \fBSPIClass::setDataMode\fP (uint8_tmode)\fC [static]\fP"
.PP
Definition at line 56 of file SPI\&.cpp\&.
.SS "byte \fBSPIClass::transfer\fP (byte_data)\fC [inline, static]\fP"
.PP
Definition at line 55 of file SPI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
