.TH "Included Libraries/twi.c" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/twi.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br
\fC#include <compat/twi\&.h>\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'pins_arduino\&.h'\fP
.br
\fC#include 'twi\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBcbi\fP(sfr, bit)   (_SFR_BYTE(sfr) &= ~_BV(bit))"
.br
.ti -1c
.RI "#define \fBsbi\fP(sfr, bit)   (_SFR_BYTE(sfr) |= _BV(bit))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtwi_init\fP (void)"
.br
.ti -1c
.RI "void \fBtwi_setAddress\fP (uint8_t address)"
.br
.ti -1c
.RI "uint8_t \fBtwi_readFrom\fP (uint8_t address, uint8_t *\fBdata\fP, uint8_t length, uint8_t sendStop)"
.br
.ti -1c
.RI "uint8_t \fBtwi_writeTo\fP (uint8_t address, uint8_t *\fBdata\fP, uint8_t length, uint8_t wait, uint8_t sendStop)"
.br
.ti -1c
.RI "uint8_t \fBtwi_transmit\fP (const uint8_t *\fBdata\fP, uint8_t length)"
.br
.ti -1c
.RI "void \fBtwi_attachSlaveRxEvent\fP (void(*function)(uint8_t *, int))"
.br
.ti -1c
.RI "void \fBtwi_attachSlaveTxEvent\fP (void(*function)(void))"
.br
.ti -1c
.RI "void \fBtwi_reply\fP (uint8_t ack)"
.br
.ti -1c
.RI "void \fBtwi_stop\fP (void)"
.br
.ti -1c
.RI "void \fBtwi_releaseBus\fP (void)"
.br
.ti -1c
.RI "\fBISR\fP (TWI_vect)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBcbi\fP(sfr, bit)   (_SFR_BYTE(sfr) &= ~_BV(bit))"
.PP
Definition at line 31 of file twi\&.c\&.
.SS "#define \fBsbi\fP(sfr, bit)   (_SFR_BYTE(sfr) |= _BV(bit))"
.PP
Definition at line 35 of file twi\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBISR\fP (TWI_vect)"
.PP
Definition at line 363 of file twi\&.c\&.
.SS "void \fBtwi_attachSlaveRxEvent\fP (void(*)(uint8_t *, int)function)"
.PP
Definition at line 295 of file twi\&.c\&.
.SS "void \fBtwi_attachSlaveTxEvent\fP (void(*)(void)function)"
.PP
Definition at line 306 of file twi\&.c\&.
.SS "void \fBtwi_init\fP (void)"
.PP
Definition at line 68 of file twi\&.c\&.
.SS "uint8_t \fBtwi_readFrom\fP (uint8_taddress, uint8_t *data, uint8_tlength, uint8_tsendStop)"
.PP
Definition at line 115 of file twi\&.c\&.
.SS "void \fBtwi_releaseBus\fP (void)"
.PP
Definition at line 354 of file twi\&.c\&.
.SS "void \fBtwi_reply\fP (uint8_tack)"
.PP
Definition at line 317 of file twi\&.c\&.
.SS "void \fBtwi_setAddress\fP (uint8_taddress)"
.PP
Definition at line 99 of file twi\&.c\&.
.SS "void \fBtwi_stop\fP (void)"
.PP
Definition at line 333 of file twi\&.c\&.
.SS "uint8_t \fBtwi_transmit\fP (const uint8_t *data, uint8_tlength)"
.PP
Definition at line 266 of file twi\&.c\&.
.SS "uint8_t \fBtwi_writeTo\fP (uint8_taddress, uint8_t *data, uint8_tlength, uint8_twait, uint8_tsendStop)"
.PP
Definition at line 192 of file twi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
