.TH "Included Libraries/Wire.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/Wire.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br
\fC#include 'Stream\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTwoWire\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBUFFER_LENGTH\fP   32"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBUFFER_LENGTH\fP   32"
.PP
Definition at line 28 of file Wire\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
