.TH "FTDIAsyncOper" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTDIAsyncOper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cdcftdi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual uint8_t \fBOnInit\fP (\fBFTDI\fP *pftdi)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file cdcftdi\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t \fBFTDIAsyncOper::OnInit\fP (\fBFTDI\fP *pftdi)\fC [pure virtual]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
