.TH "KBDLEDS" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KBDLEDS \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hidboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbmNumLock\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmCapsLock\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmScrollLock\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmCompose\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmKana\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmReserved\fP: 3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file hidboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBKBDLEDS::bmCapsLock\fP"
.PP
Definition at line 114 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDLEDS::bmCompose\fP"
.PP
Definition at line 116 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDLEDS::bmKana\fP"
.PP
Definition at line 117 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDLEDS::bmNumLock\fP"
.PP
Definition at line 113 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDLEDS::bmReserved\fP"
.PP
Definition at line 118 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDLEDS::bmScrollLock\fP"
.PP
Definition at line 115 of file hidboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
