.TH "KeyboardReportParser" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyboardReportParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hidboot\&.h>\fP
.PP
Inherits \fBHIDReportParser\fP\&.
.PP
Inherited by \fBKbdRptParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyboardReportParser\fP ()"
.br
.ti -1c
.RI "virtual void \fBParse\fP (\fBHID\fP *hid, bool is_rpt_id, uint8_t len, uint8_t *buf)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBOemToAscii\fP (uint8_t mod, uint8_t key)"
.br
.ti -1c
.RI "virtual uint8_t \fBHandleLockingKeys\fP (\fBHID\fP *hid, uint8_t key)"
.br
.ti -1c
.RI "virtual void \fBOnControlKeysChanged\fP (uint8_t before, uint8_t after)"
.br
.ti -1c
.RI "virtual void \fBOnKeyDown\fP (uint8_t mod, uint8_t key)"
.br
.ti -1c
.RI "virtual void \fBOnKeyUp\fP (uint8_t mod, uint8_t key)"
.br
.ti -1c
.RI "virtual const uint8_t * \fBgetNumKeys\fP ()"
.br
.ti -1c
.RI "virtual const uint8_t * \fBgetSymKeysUp\fP ()"
.br
.ti -1c
.RI "virtual const uint8_t * \fBgetSymKeysLo\fP ()"
.br
.ti -1c
.RI "virtual const uint8_t * \fBgetPadKeys\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBKBDINFO\fP \fBkbdInfo\fP"
.br
.ti -1c
.RI "   uint8_t \fBbInfo\fP [sizeof(\fBKBDINFO\fP)]"
.br
.ti -1c
.RI "} \fBprevState\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBKBDLEDS\fP \fBkbdLeds\fP"
.br
.ti -1c
.RI "   uint8_t \fBbLeds\fP"
.br
.ti -1c
.RI "} \fBkbdLockingKeys\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file hidboot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBKeyboardReportParser::KeyboardReportParser\fP ()\fC [inline]\fP"
.PP
Definition at line 143 of file hidboot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const uint8_t* \fBKeyboardReportParser::getNumKeys\fP ()\fC [inline, protected, virtual]\fP"
.PP
Definition at line 161 of file hidboot\&.h\&.
.SS "virtual const uint8_t* \fBKeyboardReportParser::getPadKeys\fP ()\fC [inline, protected, virtual]\fP"
.PP
Definition at line 173 of file hidboot\&.h\&.
.SS "virtual const uint8_t* \fBKeyboardReportParser::getSymKeysLo\fP ()\fC [inline, protected, virtual]\fP"
.PP
Definition at line 169 of file hidboot\&.h\&.
.SS "virtual const uint8_t* \fBKeyboardReportParser::getSymKeysUp\fP ()\fC [inline, protected, virtual]\fP"
.PP
Definition at line 165 of file hidboot\&.h\&.
.SS "uint8_t \fBKeyboardReportParser::HandleLockingKeys\fP (\fBHID\fP *hid, uint8_tkey)\fC [protected, virtual]\fP"
.PP
Reimplemented in \fBKbdRptParser\fP\&.
.PP
Definition at line 160 of file hidboot\&.cpp\&.
.SS "uint8_t \fBKeyboardReportParser::OemToAscii\fP (uint8_tmod, uint8_tkey)\fC [protected]\fP"
.PP
Definition at line 186 of file hidboot\&.cpp\&.
.SS "virtual void \fBKeyboardReportParser::OnControlKeysChanged\fP (uint8_tbefore, uint8_tafter)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBKbdRptParser\fP\&.
.PP
Definition at line 152 of file hidboot\&.h\&.
.SS "virtual void \fBKeyboardReportParser::OnKeyDown\fP (uint8_tmod, uint8_tkey)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBKbdRptParser\fP\&.
.PP
Definition at line 155 of file hidboot\&.h\&.
.SS "virtual void \fBKeyboardReportParser::OnKeyUp\fP (uint8_tmod, uint8_tkey)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBKbdRptParser\fP\&.
.PP
Definition at line 158 of file hidboot\&.h\&.
.SS "void \fBKeyboardReportParser::Parse\fP (\fBHID\fP *hid, boolis_rpt_id, uint8_tlen, uint8_t *buf)\fC [virtual]\fP"
.PP
Implements \fBHIDReportParser\fP\&.
.PP
Definition at line 127 of file hidboot\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBKeyboardReportParser::bInfo\fP[sizeof(\fBKBDINFO\fP)]"
.PP
Definition at line 131 of file hidboot\&.h\&.
.SS "uint8_t \fBKeyboardReportParser::bLeds\fP"
.PP
Definition at line 136 of file hidboot\&.h\&.
.SS "\fBKBDINFO\fP \fBKeyboardReportParser::kbdInfo\fP"
.PP
Definition at line 130 of file hidboot\&.h\&.
.SS "\fBKBDLEDS\fP \fBKeyboardReportParser::kbdLeds\fP"
.PP
Definition at line 135 of file hidboot\&.h\&.
.SS "union { \&.\&.\&. }   \fBKeyboardReportParser::kbdLockingKeys\fP\fC [protected]\fP"
.SS "union { \&.\&.\&. }   \fBKeyboardReportParser::prevState\fP\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
