.TH "RequestSenseResponce" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RequestSenseResponce \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <masstorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbResponseCode\fP"
.br
.ti -1c
.RI "uint8_t \fBbSegmentNumber\fP"
.br
.ti -1c
.RI "uint8_t \fBbmSenseKey\fP: 4"
.br
.ti -1c
.RI "uint8_t \fBbmReserved\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmILI\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmEOM\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbmFileMark\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBInformation\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBbAdditionalLength\fP"
.br
.ti -1c
.RI "uint8_t \fBCmdSpecificInformation\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBbAdditionalSenseCode\fP"
.br
.ti -1c
.RI "uint8_t \fBbAdditionalSenseQualifier\fP"
.br
.ti -1c
.RI "uint8_t \fBbFieldReplaceableUnitCode\fP"
.br
.ti -1c
.RI "uint8_t \fBSenseKeySpecific\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 443 of file masstorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBRequestSenseResponce::bAdditionalLength\fP"
.PP
Definition at line 454 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bAdditionalSenseCode\fP"
.PP
Definition at line 456 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bAdditionalSenseQualifier\fP"
.PP
Definition at line 457 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bFieldReplaceableUnitCode\fP"
.PP
Definition at line 458 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bmEOM\fP"
.PP
Definition at line 450 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bmFileMark\fP"
.PP
Definition at line 451 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bmILI\fP"
.PP
Definition at line 449 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bmReserved\fP"
.PP
Definition at line 448 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bmSenseKey\fP"
.PP
Definition at line 447 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bResponseCode\fP"
.PP
Definition at line 444 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::bSegmentNumber\fP"
.PP
Definition at line 445 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::CmdSpecificInformation\fP[4]"
.PP
Definition at line 455 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::Information\fP[4]"
.PP
Definition at line 453 of file masstorage\&.h\&.
.SS "uint8_t \fBRequestSenseResponce::SenseKeySpecific\fP[3]"
.PP
Definition at line 459 of file masstorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
