.TH "Included Libraries/SPI.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/SPI.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'pins_arduino\&.h'\fP
.br
\fC#include 'SPI\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSPIClass\fP \fBSPI\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBSPIClass\fP \fBSPI\fP"
.PP
Definition at line 14 of file SPI\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
