.TH "Included Libraries/TimerThree.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/TimerThree.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimerThree\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRESOLUTION\fP   65536"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTimerThree\fP \fBTimer3\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBRESOLUTION\fP   65536"
.PP
Definition at line 17 of file TimerThree\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBTimerThree\fP \fBTimer3\fP"
.PP
Definition at line 17 of file TimerThree\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
