.TH "CDB_LBA64_16" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDB_LBA64_16 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <masstorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBOpcode\fP"
.br
.ti -1c
.RI "uint8_t \fBMisc\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_M_M_MB\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_M_M_LB\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_M_L_MB\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_M_L_LB\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_L_M_MB\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_L_M_LB\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_L_L_MB\fP"
.br
.ti -1c
.RI "uint8_t \fBLBA_L_L_LB\fP"
.br
.ti -1c
.RI "uint8_t \fBALC_M_MB\fP"
.br
.ti -1c
.RI "uint8_t \fBALC_M_LB\fP"
.br
.ti -1c
.RI "uint8_t \fBALC_L_MB\fP"
.br
.ti -1c
.RI "uint8_t \fBALC_L_LB\fP"
.br
.ti -1c
.RI "uint8_t \fBMisc2\fP"
.br
.ti -1c
.RI "uint8_t \fBControl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 299 of file masstorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBCDB_LBA64_16::ALC_L_LB\fP"
.PP
Definition at line 316 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::ALC_L_MB\fP"
.PP
Definition at line 315 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::ALC_M_LB\fP"
.PP
Definition at line 314 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::ALC_M_MB\fP"
.PP
Definition at line 313 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::Control\fP"
.PP
Definition at line 319 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_L_L_LB\fP"
.PP
Definition at line 311 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_L_L_MB\fP"
.PP
Definition at line 310 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_L_M_LB\fP"
.PP
Definition at line 309 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_L_M_MB\fP"
.PP
Definition at line 308 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_M_L_LB\fP"
.PP
Definition at line 306 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_M_L_MB\fP"
.PP
Definition at line 305 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_M_M_LB\fP"
.PP
Definition at line 304 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::LBA_M_M_MB\fP"
.PP
Definition at line 303 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::Misc\fP"
.PP
Definition at line 301 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::Misc2\fP"
.PP
Definition at line 318 of file masstorage\&.h\&.
.SS "uint8_t \fBCDB_LBA64_16::Opcode\fP"
.PP
Definition at line 300 of file masstorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
