.TH "GHID API/GHID_UART.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID API/GHID_UART.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <avr/io\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBserial_settings_t\fP"
.br
.RI "\fIThis is a container for the serial settings\&. \fP"
.ti -1c
.RI "class \fBGHID_UART\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__AVR_ATmega2560__\fP"
.br
.ti -1c
.RI "#define \fBHARDWARE_SERIAL_FLAG\fP   0"
.br
.RI "\fIWe deine the HARDWARE flag, and the SOFTWARE flag\&. \fP"
.ti -1c
.RI "#define \fBSOFTWARE_SERIAL_FLAG\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBqword\fP"
.br
.RI "\fIDefinition of a quadword\&. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fB__AVR_ATmega2560__\fP"
.PP
Definition at line 11 of file GHID_UART\&.h\&.
.SS "#define \fBHARDWARE_SERIAL_FLAG\fP   0"
.PP
We deine the HARDWARE flag, and the SOFTWARE flag\&. 
.PP
Definition at line 17 of file GHID_UART\&.h\&.
.SS "#define \fBSOFTWARE_SERIAL_FLAG\fP   1"
.PP
Definition at line 18 of file GHID_UART\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef uint32_t \fBqword\fP"
.PP
Definition of a quadword\&. 
.PP
Definition at line 21 of file GHID_UART\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
