.TH "GHID API/GHID_SPI.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID API/GHID_SPI.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GHID_SPI\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBISR\fP (SPI_STC_vect)"
.br
.RI "\fIIf the interrupt is online\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBISR\fP (SPI_STC_vect)"
.PP
If the interrupt is online\&. Get a buffered char
.PP
If not full
.PP
We add one more byte to the array 
.PP
Definition at line 87 of file GHID_SPI\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
