.TH "HIDBoot< BOOT_PROTOCOL >" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HIDBoot< BOOT_PROTOCOL > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hidboot\&.h>\fP
.PP
Inherits \fBHID\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHIDBoot\fP (USB *p)"
.br
.ti -1c
.RI "virtual bool \fBSetReportParser\fP (uint8_t id, \fBHIDReportParser\fP *prs)"
.br
.ti -1c
.RI "virtual uint8_t \fBInit\fP (uint8_t parent, uint8_t port, bool lowspeed)"
.br
.ti -1c
.RI "virtual uint8_t \fBRelease\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBPoll\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBGetAddress\fP ()"
.br
.ti -1c
.RI "virtual void \fBEndpointXtract\fP (uint8_t conf, uint8_t iface, uint8_t alt, uint8_t proto, const USB_ENDPOINT_DESCRIPTOR *ep)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<const uint8_t BOOT_PROTOCOL>class HIDBoot< BOOT_PROTOCOL >"

.PP
Definition at line 179 of file hidboot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<const uint8_t BOOT_PROTOCOL> \fBHIDBoot\fP< BOOT_PROTOCOL >::\fBHIDBoot\fP (USB *p)"
.PP
Definition at line 220 of file hidboot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<const uint8_t BOOT_PROTOCOL> void \fBHIDBoot\fP< BOOT_PROTOCOL >::\fBEndpointXtract\fP (uint8_tconf, uint8_tiface, uint8_talt, uint8_tproto, const USB_ENDPOINT_DESCRIPTOR *ep)\fC [virtual]\fP"
.PP
Definition at line 498 of file hidboot\&.h\&.
.SS "template<const uint8_t BOOT_PROTOCOL> virtual uint8_t \fBHIDBoot\fP< BOOT_PROTOCOL >::\fBGetAddress\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 211 of file hidboot\&.h\&.
.SS "template<const uint8_t BOOT_PROTOCOL> uint8_t \fBHIDBoot\fP< BOOT_PROTOCOL >::\fBInit\fP (uint8_tparent, uint8_tport, boollowspeed)\fC [virtual]\fP"
.PP
Definition at line 247 of file hidboot\&.h\&.
.SS "template<const uint8_t BOOT_PROTOCOL> uint8_t \fBHIDBoot\fP< BOOT_PROTOCOL >::\fBPoll\fP ()\fC [virtual]\fP"
.PP
Definition at line 536 of file hidboot\&.h\&.
.SS "template<const uint8_t BOOT_PROTOCOL> uint8_t \fBHIDBoot\fP< BOOT_PROTOCOL >::\fBRelease\fP ()\fC [virtual]\fP"
.PP
Definition at line 522 of file hidboot\&.h\&.
.SS "template<const uint8_t BOOT_PROTOCOL> virtual bool \fBHIDBoot\fP< BOOT_PROTOCOL >::\fBSetReportParser\fP (uint8_tid, \fBHIDReportParser\fP *prs)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBHID\fP\&.
.PP
Definition at line 201 of file hidboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
