.TH "LINE_CODING" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LINE_CODING \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cdcacm\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdwDTERate\fP"
.br
.ti -1c
.RI "uint8_t \fBbCharFormat\fP"
.br
.ti -1c
.RI "uint8_t \fBbParityType\fP"
.br
.ti -1c
.RI "uint8_t \fBbDataBits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file cdcacm\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBLINE_CODING::bCharFormat\fP"
.PP
Definition at line 112 of file cdcacm\&.h\&.
.SS "uint8_t \fBLINE_CODING::bDataBits\fP"
.PP
Definition at line 114 of file cdcacm\&.h\&.
.SS "uint8_t \fBLINE_CODING::bParityType\fP"
.PP
Definition at line 113 of file cdcacm\&.h\&.
.SS "uint32_t \fBLINE_CODING::dwDTERate\fP"
.PP
Definition at line 111 of file cdcacm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
