.TH "Included Libraries/USB_Host_Shield_2.0-master/settings.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/settings.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'macros\&.h'\fP
.br
\fC#include <WProgram\&.h>\fP
.br
\fC#include <pins_arduino\&.h>\fP
.br
\fC#include <avr/pgmspace\&.h>\fP
.br
\fC#include <avr/io\&.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBENABLE_UHS_DEBUGGING\fP   0"
.br
.ti -1c
.RI "#define \fBUSE_UHS_MEGA_ADK\fP   0"
.br
.ti -1c
.RI "#define \fBUSE_UHS_BLACK_WIDDOW\fP   0"
.br
.ti -1c
.RI "#define \fBUSE_XMEM_SPI_LOCK\fP   0"
.br
.ti -1c
.RI "#define \fBENABLE_WII_IR_CAMERA\fP   0"
.br
.ti -1c
.RI "#define \fBF\fP(str)   (str)"
.br
.ti -1c
.RI "#define \fBEXT_RAM\fP   0"
.br
.ti -1c
.RI "#define \fBUSING_SPI4TEENSY3\fP   0"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBENABLE_UHS_DEBUGGING\fP   0"
.PP
Definition at line 17 of file settings\&.h\&.
.SS "#define \fBENABLE_WII_IR_CAMERA\fP   0"
.PP
Definition at line 45 of file settings\&.h\&.
.SS "#define \fBEXT_RAM\fP   0"
.PP
Definition at line 121 of file settings\&.h\&.
.SS "#define \fBF\fP(str)   (str)"
.PP
Definition at line 78 of file settings\&.h\&.
.SS "#define \fBUSE_UHS_BLACK_WIDDOW\fP   0"
.PP
Definition at line 35 of file settings\&.h\&.
.SS "#define \fBUSE_UHS_MEGA_ADK\fP   0"
.PP
Definition at line 32 of file settings\&.h\&.
.SS "#define \fBUSE_XMEM_SPI_LOCK\fP   0"
.PP
Definition at line 38 of file settings\&.h\&.
.SS "#define \fBUSING_SPI4TEENSY3\fP   0"
.PP
Definition at line 127 of file settings\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
