.TH "Included Libraries/USB_Host_Shield_2.0-master/BTHID.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/BTHID.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BTD\&.h'\fP
.br
\fC#include 'hidboot\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBTHID\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBKEYBOARD_PARSER_ID\fP   0"
.br
.ti -1c
.RI "#define \fBMOUSE_PARSER_ID\fP   1"
.br
.ti -1c
.RI "#define \fBNUM_PARSERS\fP   2"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBKEYBOARD_PARSER_ID\fP   0"
.PP
Definition at line 24 of file BTHID\&.h\&.
.SS "#define \fBMOUSE_PARSER_ID\fP   1"
.PP
Definition at line 25 of file BTHID\&.h\&.
.SS "#define \fBNUM_PARSERS\fP   2"
.PP
Definition at line 26 of file BTHID\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
