.TH "CLASS_NOTIFICATION" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLASS_NOTIFICATION \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cdcacm\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbmRequestType\fP"
.br
.ti -1c
.RI "uint8_t \fBbNotification\fP"
.br
.ti -1c
.RI "uint16_t \fBwValue\fP"
.br
.ti -1c
.RI "uint16_t \fBwIndex\fP"
.br
.ti -1c
.RI "uint16_t \fBwLength\fP"
.br
.ti -1c
.RI "uint16_t \fBbmState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 117 of file cdcacm\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBCLASS_NOTIFICATION::bmRequestType\fP"
.PP
Definition at line 118 of file cdcacm\&.h\&.
.SS "uint16_t \fBCLASS_NOTIFICATION::bmState\fP"
.PP
Definition at line 123 of file cdcacm\&.h\&.
.SS "uint8_t \fBCLASS_NOTIFICATION::bNotification\fP"
.PP
Definition at line 119 of file cdcacm\&.h\&.
.SS "uint16_t \fBCLASS_NOTIFICATION::wIndex\fP"
.PP
Definition at line 121 of file cdcacm\&.h\&.
.SS "uint16_t \fBCLASS_NOTIFICATION::wLength\fP"
.PP
Definition at line 122 of file cdcacm\&.h\&.
.SS "uint16_t \fBCLASS_NOTIFICATION::wValue\fP"
.PP
Definition at line 120 of file cdcacm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
