.TH "GHID API/GHID_USB_Structures.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID API/GHID_USB_Structures.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GHID_System_Abstration\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBjoystick_report_t\fP"
.br
.RI "\fIIf the mouse is chosen\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
