.TH "GHID API/GHID_Dallas_1_Wire.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID API/GHID_Dallas_1_Wire.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'OneWire\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbuffer_struct_t\fP"
.br
.RI "\fIBuffer structure\&. \fP"
.ti -1c
.RI "class \fBGHID_Dallas_1_Wire\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_BUFFER\fP   255"
.br
.RI "\fIMax buffer size\&. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMAX_BUFFER\fP   255"
.PP
Max buffer size\&. 
.PP
Definition at line 14 of file GHID_Dallas_1_Wire\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
