.TH "HIDReportParser" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HIDReportParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hid\&.h>\fP
.PP
Inherited by \fBKeyboardReportParser\fP, \fBMouseReportParser\fP, and \fBUniversalReportParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBParse\fP (\fBHID\fP *hid, bool is_rpt_id, uint8_t len, uint8_t *buf)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 138 of file hid\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void \fBHIDReportParser::Parse\fP (\fBHID\fP *hid, boolis_rpt_id, uint8_tlen, uint8_t *buf)\fC [pure virtual]\fP"
.PP
Implemented in \fBUniversalReportParser\fP, \fBKeyboardReportParser\fP, and \fBMouseReportParser\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
