.TH "Max_LCD" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Max_LCD \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <max_LCD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMax_LCD\fP (USB *pusb)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBbegin\fP (uint8_t cols, uint8_t rows, uint8_t charsize=\fBLCD_5x8DOTS\fP)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBhome\fP ()"
.br
.ti -1c
.RI "void \fBnoDisplay\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.ti -1c
.RI "void \fBnoBlink\fP ()"
.br
.ti -1c
.RI "void \fBblink\fP ()"
.br
.ti -1c
.RI "void \fBnoCursor\fP ()"
.br
.ti -1c
.RI "void \fBcursor\fP ()"
.br
.ti -1c
.RI "void \fBscrollDisplayLeft\fP ()"
.br
.ti -1c
.RI "void \fBscrollDisplayRight\fP ()"
.br
.ti -1c
.RI "void \fBleftToRight\fP ()"
.br
.ti -1c
.RI "void \fBrightToLeft\fP ()"
.br
.ti -1c
.RI "void \fBautoscroll\fP ()"
.br
.ti -1c
.RI "void \fBnoAutoscroll\fP ()"
.br
.ti -1c
.RI "void \fBcreateChar\fP (uint8_t, uint8_t[])"
.br
.ti -1c
.RI "void \fBsetCursor\fP (uint8_t, uint8_t)"
.br
.ti -1c
.RI "void \fBcommand\fP (uint8_t)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint8_t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file max_LCD\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBMax_LCD::Max_LCD\fP (USB *pusb)"
.PP
Definition at line 42 of file max_LCD\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBMax_LCD::autoscroll\fP (void)"
.PP
Definition at line 196 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::begin\fP (uint8_tcols, uint8_trows, uint8_tcharsize = \fC\fBLCD_5x8DOTS\fP\fP)"
.PP
Definition at line 54 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::blink\fP ()"
.PP
Definition at line 165 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::clear\fP ()"
.PP
Definition at line 114 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::command\fP (uint8_tvalue)\fC [inline]\fP"
.PP
Definition at line 221 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::createChar\fP (uint8_tlocation, uint8_tcharmap[])"
.PP
Definition at line 211 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::cursor\fP ()"
.PP
Definition at line 152 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::display\fP ()"
.PP
Definition at line 140 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::home\fP ()"
.PP
Definition at line 119 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::init\fP ()"
.PP
Definition at line 46 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::leftToRight\fP (void)"
.PP
Definition at line 182 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::noAutoscroll\fP (void)"
.PP
Definition at line 203 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::noBlink\fP ()"
.PP
Definition at line 160 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::noCursor\fP ()"
.PP
Definition at line 147 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::noDisplay\fP ()"
.PP
Definition at line 135 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::rightToLeft\fP (void)"
.PP
Definition at line 189 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::scrollDisplayLeft\fP (void)"
.PP
Definition at line 172 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::scrollDisplayRight\fP (void)"
.PP
Definition at line 176 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::setCursor\fP (uint8_tcol, uint8_trow)"
.PP
Definition at line 124 of file max_LCD\&.cpp\&.
.SS "void \fBMax_LCD::write\fP (uint8_tvalue)\fC [inline, virtual]\fP"
.PP
Definition at line 234 of file max_LCD\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
