.TH "MOUSEINFO" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MOUSEINFO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hidboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBbmLeftButton\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmRightButton\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmMiddleButton\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmDummy\fP: 5"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "int8_t \fBdX\fP"
.br
.ti -1c
.RI "int8_t \fBdY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file hidboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. } "
.SS "uint8_t \fBMOUSEINFO::bmDummy\fP"
.PP
Definition at line 45 of file hidboot\&.h\&.
.SS "uint8_t \fBMOUSEINFO::bmLeftButton\fP"
.PP
Definition at line 42 of file hidboot\&.h\&.
.SS "uint8_t \fBMOUSEINFO::bmMiddleButton\fP"
.PP
Definition at line 44 of file hidboot\&.h\&.
.SS "uint8_t \fBMOUSEINFO::bmRightButton\fP"
.PP
Definition at line 43 of file hidboot\&.h\&.
.SS "int8_t \fBMOUSEINFO::dX\fP"
.PP
Definition at line 47 of file hidboot\&.h\&.
.SS "int8_t \fBMOUSEINFO::dY\fP"
.PP
Definition at line 48 of file hidboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
