.TH "Included Libraries/USB_Host_Shield_2.0-master/PS3BT.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/PS3BT.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BTD\&.h'\fP
.br
\fC#include 'PS3Enums\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPS3BT\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHID_BUFFERSIZE\fP   50"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBHID_BUFFERSIZE\fP   50"
.PP
Definition at line 24 of file PS3BT\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
