.TH "PS4Buttons" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS4Buttons \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PS4Parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBdpad\fP: 4"
.br
.ti -1c
.RI "   uint8_t \fBsquare\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBcross\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBcircle\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBtriangle\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBl1\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBr1\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBl2\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBr2\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBshare\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBoptions\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBl3\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBr3\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBps\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBtouchpad\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBreportCounter\fP: 6"
.br
.ti -1c
.RI "} \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBval\fP: 24"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file PS4Parser\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "struct PS4Buttons::@20 \fBPS4Buttons::__attribute__\fP ((packed))"
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBPS4Buttons::circle\fP"
.PP
Definition at line 55 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::cross\fP"
.PP
Definition at line 54 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::dpad\fP"
.PP
Definition at line 52 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::l1\fP"
.PP
Definition at line 58 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::l2\fP"
.PP
Definition at line 60 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::l3\fP"
.PP
Definition at line 64 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::options\fP"
.PP
Definition at line 63 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::ps\fP"
.PP
Definition at line 67 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::r1\fP"
.PP
Definition at line 59 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::r2\fP"
.PP
Definition at line 61 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::r3\fP"
.PP
Definition at line 65 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::reportCounter\fP"
.PP
Definition at line 69 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::share\fP"
.PP
Definition at line 62 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::square\fP"
.PP
Definition at line 53 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::touchpad\fP"
.PP
Definition at line 68 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Buttons::triangle\fP"
.PP
Definition at line 56 of file PS4Parser\&.h\&.
.SS "uint32_t \fBPS4Buttons::val\fP"
.PP
Definition at line 71 of file PS4Parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
