.TH "PS4Output" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS4Output \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PS4Parser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbigRumble\fP"
.br
.ti -1c
.RI "uint8_t \fBsmallRumble\fP"
.br
.ti -1c
.RI "uint8_t \fBr\fP"
.br
.ti -1c
.RI "uint8_t \fBg\fP"
.br
.ti -1c
.RI "uint8_t \fBb\fP"
.br
.ti -1c
.RI "uint8_t \fBflashOn\fP"
.br
.ti -1c
.RI "uint8_t \fBflashOff\fP"
.br
.ti -1c
.RI "bool \fBreportChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 105 of file PS4Parser\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBPS4Output::b\fP"
.PP
Definition at line 107 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Output::bigRumble\fP"
.PP
Definition at line 106 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Output::flashOff\fP"
.PP
Definition at line 108 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Output::flashOn\fP"
.PP
Definition at line 108 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Output::g\fP"
.PP
Definition at line 107 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Output::r\fP"
.PP
Definition at line 107 of file PS4Parser\&.h\&.
.SS "bool \fBPS4Output::reportChanged\fP"
.PP
Definition at line 109 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Output::smallRumble\fP"
.PP
Definition at line 106 of file PS4Parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
