.TH "spi_settings_t" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spi_settings_t \- 
.PP
SPI device settings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GHID_SPI\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBattach_interrupt\fP"
.br
.ti -1c
.RI "byte \fBdata_mode\fP"
.br
.RI "\fIdo we attach an interrupt on the SPI bus? \fP"
.ti -1c
.RI "byte \fBbit_order\fP"
.br
.RI "\fIThe data mode as per Arduino API\&. \fP"
.ti -1c
.RI "byte \fBclock_divider\fP"
.br
.RI "\fIThe order of bits\&. \fP"
.ti -1c
.RI "\fBspi_device_address_map_t\fP \fBmap\fP"
.br
.RI "\fIFrequency prescaler\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
SPI device settings\&. 
.PP
Definition at line 42 of file GHID_SPI\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "byte \fBspi_settings_t::attach_interrupt\fP"
.PP
Definition at line 44 of file GHID_SPI\&.h\&.
.SS "byte \fBspi_settings_t::bit_order\fP"
.PP
The data mode as per Arduino API\&. 
.PP
Definition at line 47 of file GHID_SPI\&.h\&.
.SS "byte \fBspi_settings_t::clock_divider\fP"
.PP
The order of bits\&. 
.PP
Definition at line 48 of file GHID_SPI\&.h\&.
.SS "byte \fBspi_settings_t::data_mode\fP"
.PP
do we attach an interrupt on the SPI bus? 
.PP
Definition at line 46 of file GHID_SPI\&.h\&.
.SS "\fBspi_device_address_map_t\fP \fBspi_settings_t::map\fP"
.PP
Frequency prescaler\&. 
.PP
Definition at line 49 of file GHID_SPI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
