.TH "touchpadXY" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
touchpadXY \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PS4Parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBcounter\fP: 7"
.br
.ti -1c
.RI "   uint8_t \fBtouching\fP: 1"
.br
.ti -1c
.RI "   uint16_t \fBx\fP: 12"
.br
.ti -1c
.RI "   uint16_t \fBy\fP: 12"
.br
.ti -1c
.RI "} \fB__attribute__\fP ((packed)) finger[2]"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBdummy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file PS4Parser\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "struct touchpadXY::@22 \fBtouchpadXY::__attribute__\fP ((packed))"
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBtouchpadXY::counter\fP"
.PP
Definition at line 77 of file PS4Parser\&.h\&.
.SS "uint8_t \fBtouchpadXY::dummy\fP"
.PP
Definition at line 75 of file PS4Parser\&.h\&.
.SS "uint8_t \fBtouchpadXY::touching\fP"
.PP
Definition at line 78 of file PS4Parser\&.h\&.
.SS "uint16_t \fBtouchpadXY::x\fP"
.PP
Definition at line 79 of file PS4Parser\&.h\&.
.SS "uint16_t \fBtouchpadXY::y\fP"
.PP
Definition at line 80 of file PS4Parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
