.TH "Included Libraries/USB_Host_Shield_2.0-master/hidusagestr.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/hidusagestr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char pstrSpace[] \fBPROGMEM\fP = ' '"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char pstrUsageSoftControlAdjust [] \fBPROGMEM\fP = ' '"
.PP
Definition at line 22 of file hidusagestr\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
