.TH "HubEvent" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HubEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usbhub\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   uint32_t \fBbmEvent\fP"
.br
.ti -1c
.RI "   uint8_t \fBevtBuff\fP [4]"
.br
.ti -1c
.RI "} \fB__attribute__\fP"
.br
.ti -1c
.RI "uint16_t \fBbmStatus\fP"
.br
.ti -1c
.RI "uint16_t \fBbmChange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 151 of file usbhub\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "union { \&.\&.\&. }   \fBHubEvent::__attribute__\fP"
.SS "uint16_t \fBHubEvent::bmChange\fP"
.PP
Definition at line 157 of file usbhub\&.h\&.
.SS "uint32_t \fBHubEvent::bmEvent\fP"
.PP
Definition at line 159 of file usbhub\&.h\&.
.SS "uint16_t \fBHubEvent::bmStatus\fP"
.PP
Definition at line 156 of file usbhub\&.h\&.
.SS "uint8_t \fBHubEvent::evtBuff\fP[4]"
.PP
Definition at line 160 of file usbhub\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
