.TH "Included Libraries/USB_Host_Shield_2.0-master/max_LCD.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/max_LCD.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br
\fC#include 'Print\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMax_LCD\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLCD_CLEARDISPLAY\fP   0x01"
.br
.ti -1c
.RI "#define \fBLCD_RETURNHOME\fP   0x02"
.br
.ti -1c
.RI "#define \fBLCD_ENTRYMODESET\fP   0x04"
.br
.ti -1c
.RI "#define \fBLCD_DISPLAYCONTROL\fP   0x08"
.br
.ti -1c
.RI "#define \fBLCD_CURSORSHIFT\fP   0x10"
.br
.ti -1c
.RI "#define \fBLCD_FUNCTIONSET\fP   0x20"
.br
.ti -1c
.RI "#define \fBLCD_SETCGRAMADDR\fP   0x40"
.br
.ti -1c
.RI "#define \fBLCD_SETDDRAMADDR\fP   0x80"
.br
.ti -1c
.RI "#define \fBLCD_ENTRYRIGHT\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_ENTRYLEFT\fP   0x02"
.br
.ti -1c
.RI "#define \fBLCD_ENTRYSHIFTINCREMENT\fP   0x01"
.br
.ti -1c
.RI "#define \fBLCD_ENTRYSHIFTDECREMENT\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_DISPLAYON\fP   0x04"
.br
.ti -1c
.RI "#define \fBLCD_DISPLAYOFF\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_CURSORON\fP   0x02"
.br
.ti -1c
.RI "#define \fBLCD_CURSOROFF\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_BLINKON\fP   0x01"
.br
.ti -1c
.RI "#define \fBLCD_BLINKOFF\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_DISPLAYMOVE\fP   0x08"
.br
.ti -1c
.RI "#define \fBLCD_CURSORMOVE\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_MOVERIGHT\fP   0x04"
.br
.ti -1c
.RI "#define \fBLCD_MOVELEFT\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_8BITMODE\fP   0x10"
.br
.ti -1c
.RI "#define \fBLCD_4BITMODE\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_2LINE\fP   0x08"
.br
.ti -1c
.RI "#define \fBLCD_1LINE\fP   0x00"
.br
.ti -1c
.RI "#define \fBLCD_5x10DOTS\fP   0x04"
.br
.ti -1c
.RI "#define \fBLCD_5x8DOTS\fP   0x00"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBLCD_1LINE\fP   0x00"
.PP
Definition at line 61 of file max_LCD\&.h\&.
.SS "#define \fBLCD_2LINE\fP   0x08"
.PP
Definition at line 60 of file max_LCD\&.h\&.
.SS "#define \fBLCD_4BITMODE\fP   0x00"
.PP
Definition at line 59 of file max_LCD\&.h\&.
.SS "#define \fBLCD_5x10DOTS\fP   0x04"
.PP
Definition at line 62 of file max_LCD\&.h\&.
.SS "#define \fBLCD_5x8DOTS\fP   0x00"
.PP
Definition at line 63 of file max_LCD\&.h\&.
.SS "#define \fBLCD_8BITMODE\fP   0x10"
.PP
Definition at line 58 of file max_LCD\&.h\&.
.SS "#define \fBLCD_BLINKOFF\fP   0x00"
.PP
Definition at line 49 of file max_LCD\&.h\&.
.SS "#define \fBLCD_BLINKON\fP   0x01"
.PP
Definition at line 48 of file max_LCD\&.h\&.
.SS "#define \fBLCD_CLEARDISPLAY\fP   0x01"
.PP
Definition at line 28 of file max_LCD\&.h\&.
.SS "#define \fBLCD_CURSORMOVE\fP   0x00"
.PP
Definition at line 53 of file max_LCD\&.h\&.
.SS "#define \fBLCD_CURSOROFF\fP   0x00"
.PP
Definition at line 47 of file max_LCD\&.h\&.
.SS "#define \fBLCD_CURSORON\fP   0x02"
.PP
Definition at line 46 of file max_LCD\&.h\&.
.SS "#define \fBLCD_CURSORSHIFT\fP   0x10"
.PP
Definition at line 32 of file max_LCD\&.h\&.
.SS "#define \fBLCD_DISPLAYCONTROL\fP   0x08"
.PP
Definition at line 31 of file max_LCD\&.h\&.
.SS "#define \fBLCD_DISPLAYMOVE\fP   0x08"
.PP
Definition at line 52 of file max_LCD\&.h\&.
.SS "#define \fBLCD_DISPLAYOFF\fP   0x00"
.PP
Definition at line 45 of file max_LCD\&.h\&.
.SS "#define \fBLCD_DISPLAYON\fP   0x04"
.PP
Definition at line 44 of file max_LCD\&.h\&.
.SS "#define \fBLCD_ENTRYLEFT\fP   0x02"
.PP
Definition at line 39 of file max_LCD\&.h\&.
.SS "#define \fBLCD_ENTRYMODESET\fP   0x04"
.PP
Definition at line 30 of file max_LCD\&.h\&.
.SS "#define \fBLCD_ENTRYRIGHT\fP   0x00"
.PP
Definition at line 38 of file max_LCD\&.h\&.
.SS "#define \fBLCD_ENTRYSHIFTDECREMENT\fP   0x00"
.PP
Definition at line 41 of file max_LCD\&.h\&.
.SS "#define \fBLCD_ENTRYSHIFTINCREMENT\fP   0x01"
.PP
Definition at line 40 of file max_LCD\&.h\&.
.SS "#define \fBLCD_FUNCTIONSET\fP   0x20"
.PP
Definition at line 33 of file max_LCD\&.h\&.
.SS "#define \fBLCD_MOVELEFT\fP   0x00"
.PP
Definition at line 55 of file max_LCD\&.h\&.
.SS "#define \fBLCD_MOVERIGHT\fP   0x04"
.PP
Definition at line 54 of file max_LCD\&.h\&.
.SS "#define \fBLCD_RETURNHOME\fP   0x02"
.PP
Definition at line 29 of file max_LCD\&.h\&.
.SS "#define \fBLCD_SETCGRAMADDR\fP   0x40"
.PP
Definition at line 34 of file max_LCD\&.h\&.
.SS "#define \fBLCD_SETDDRAMADDR\fP   0x80"
.PP
Definition at line 35 of file max_LCD\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
