.TH "Included Libraries/USB_Host_Shield_2.0-master/message.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/message.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBE_Notifyc\fP (char c, int lvl)"
.br
.ti -1c
.RI "void \fBE_Notify\fP (char const *msg, int lvl)"
.br
.ti -1c
.RI "void \fBE_NotifyStr\fP (char const *msg, int lvl)"
.br
.ti -1c
.RI "void \fBE_Notify\fP (uint8_t \fBb\fP, int lvl)"
.br
.ti -1c
.RI "void \fBE_Notify\fP (double d, int lvl)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBUsbDEBUGlvl\fP = 0x80"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBE_Notify\fP (char const *msg, intlvl)"
.PP
Definition at line 34 of file message\&.cpp\&.
.SS "void \fBE_Notify\fP (uint8_tb, intlvl)"
.PP
Definition at line 50 of file message\&.cpp\&.
.SS "void \fBE_Notify\fP (doubled, intlvl)"
.PP
Definition at line 60 of file message\&.cpp\&.
.SS "void \fBE_Notifyc\fP (charc, intlvl)"
.PP
Definition at line 24 of file message\&.cpp\&.
.SS "void \fBE_NotifyStr\fP (char const *msg, intlvl)"
.PP
Definition at line 42 of file message\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int \fBUsbDEBUGlvl\fP = 0x80"
.PP
Definition at line 22 of file message\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
