.TH "MouseRptParser" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MouseRptParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MouseParser\&.h>\fP
.PP
Inherits \fBMouseReportParser\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnMouseMove\fP (\fBMOUSEINFO\fP *mi)"
.br
.ti -1c
.RI "virtual void \fBOnLeftButtonUp\fP (\fBMOUSEINFO\fP *mi)"
.br
.ti -1c
.RI "virtual void \fBOnLeftButtonDown\fP (\fBMOUSEINFO\fP *mi)"
.br
.ti -1c
.RI "virtual void \fBOnRightButtonUp\fP (\fBMOUSEINFO\fP *mi)"
.br
.ti -1c
.RI "virtual void \fBOnRightButtonDown\fP (\fBMOUSEINFO\fP *mi)"
.br
.ti -1c
.RI "virtual void \fBOnMiddleButtonUp\fP (\fBMOUSEINFO\fP *mi)"
.br
.ti -1c
.RI "virtual void \fBOnMiddleButtonDown\fP (\fBMOUSEINFO\fP *mi)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file MouseParser\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBMouseRptParser::OnLeftButtonDown\fP (\fBMOUSEINFO\fP *mi)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBMouseReportParser\fP\&.
.PP
Definition at line 26 of file MouseParser\&.h\&.
.SS "void \fBMouseRptParser::OnLeftButtonUp\fP (\fBMOUSEINFO\fP *mi)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBMouseReportParser\fP\&.
.PP
Definition at line 22 of file MouseParser\&.h\&.
.SS "void \fBMouseRptParser::OnMiddleButtonDown\fP (\fBMOUSEINFO\fP *mi)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBMouseReportParser\fP\&.
.PP
Definition at line 42 of file MouseParser\&.h\&.
.SS "void \fBMouseRptParser::OnMiddleButtonUp\fP (\fBMOUSEINFO\fP *mi)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBMouseReportParser\fP\&.
.PP
Definition at line 38 of file MouseParser\&.h\&.
.SS "void \fBMouseRptParser::OnMouseMove\fP (\fBMOUSEINFO\fP *mi)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBMouseReportParser\fP\&.
.PP
Definition at line 15 of file MouseParser\&.h\&.
.SS "void \fBMouseRptParser::OnRightButtonDown\fP (\fBMOUSEINFO\fP *mi)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBMouseReportParser\fP\&.
.PP
Definition at line 34 of file MouseParser\&.h\&.
.SS "void \fBMouseRptParser::OnRightButtonUp\fP (\fBMOUSEINFO\fP *mi)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBMouseReportParser\fP\&.
.PP
Definition at line 30 of file MouseParser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
