.TH "OneWire" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OneWire \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OneWire\&.h>\fP
.PP
Inherited by \fBGHID_Dallas_1_Wire\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOneWire\fP (uint8_t pin)"
.br
.ti -1c
.RI "uint8_t \fBreset\fP (void)"
.br
.ti -1c
.RI "void \fBselect\fP (const uint8_t rom[8])"
.br
.ti -1c
.RI "void \fBskip\fP (void)"
.br
.ti -1c
.RI "void \fBwrite\fP (uint8_t v, uint8_t power=0)"
.br
.ti -1c
.RI "void \fBwrite_bytes\fP (const uint8_t *buf, uint16_t count, bool power=0)"
.br
.ti -1c
.RI "uint8_t \fBread\fP (void)"
.br
.ti -1c
.RI "void \fBread_bytes\fP (uint8_t *buf, uint16_t count)"
.br
.ti -1c
.RI "void \fBwrite_bit\fP (uint8_t v)"
.br
.ti -1c
.RI "uint8_t \fBread_bit\fP (void)"
.br
.ti -1c
.RI "void \fBdepower\fP (void)"
.br
.ti -1c
.RI "void \fBreset_search\fP ()"
.br
.ti -1c
.RI "void \fBtarget_search\fP (uint8_t family_code)"
.br
.ti -1c
.RI "uint8_t \fBsearch\fP (uint8_t *newAddr)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint8_t \fBcrc8\fP (const uint8_t *addr, uint8_t len)"
.br
.ti -1c
.RI "static bool \fBcheck_crc16\fP (const uint8_t *input, uint16_t len, const uint8_t *inverted_crc, uint16_t crc=0)"
.br
.ti -1c
.RI "static uint16_t \fBcrc16\fP (const uint8_t *input, uint16_t len, uint16_t crc=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file OneWire\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBOneWire::OneWire\fP (uint8_tpin)"
.PP
Definition at line 120 of file OneWire\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool \fBOneWire::check_crc16\fP (const uint8_t *input, uint16_tlen, const uint8_t *inverted_crc, uint16_tcrc = \fC0\fP)\fC [static]\fP"
.PP
Definition at line 527 of file OneWire\&.cpp\&.
.SS "uint16_t \fBOneWire::crc16\fP (const uint8_t *input, uint16_tlen, uint16_tcrc = \fC0\fP)\fC [static]\fP"
.PP
Definition at line 533 of file OneWire\&.cpp\&.
.SS "uint8_t \fBOneWire::crc8\fP (const uint8_t *addr, uint8_tlen)\fC [static]\fP"
.PP
Definition at line 495 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::depower\fP (void)"
.PP
Definition at line 287 of file OneWire\&.cpp\&.
.SS "uint8_t \fBOneWire::read\fP (void)"
.PP
Definition at line 252 of file OneWire\&.cpp\&.
.SS "uint8_t \fBOneWire::read_bit\fP (void)"
.PP
Definition at line 199 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::read_bytes\fP (uint8_t *buf, uint16_tcount)"
.PP
Definition at line 262 of file OneWire\&.cpp\&.
.SS "uint8_t \fBOneWire::reset\fP (void)"
.PP
Definition at line 137 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::reset_search\fP ()"
.PP
Definition at line 300 of file OneWire\&.cpp\&.
.SS "uint8_t \fBOneWire::search\fP (uint8_t *newAddr)"
.PP
Definition at line 342 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::select\fP (const uint8_trom[8])"
.PP
Definition at line 270 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::skip\fP (void)"
.PP
Definition at line 282 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::target_search\fP (uint8_tfamily_code)"
.PP
Definition at line 315 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::write\fP (uint8_tv, uint8_tpower = \fC0\fP)"
.PP
Definition at line 224 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::write_bit\fP (uint8_tv)"
.PP
Definition at line 171 of file OneWire\&.cpp\&.
.SS "void \fBOneWire::write_bytes\fP (const uint8_t *buf, uint16_tcount, boolpower = \fC0\fP)"
.PP
Definition at line 238 of file OneWire\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
