.TH "Included Libraries/USB_Host_Shield_2.0-master/examples/USB_desc/pgmstrings.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/examples/USB_desc/pgmstrings.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOBYTE\fP(\fBx\fP)   ((char*)(&(\fBx\fP)))[0]"
.br
.ti -1c
.RI "#define \fBHIBYTE\fP(\fBx\fP)   ((char*)(&(\fBx\fP)))[1]"
.br
.ti -1c
.RI "#define \fBBUFSIZE\fP   256"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char Gen_Error_str[] \fBPROGMEM\fP = '\\r\\nRequest error\&. Error code:\\t'"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBUFSIZE\fP   256"
.PP
Definition at line 6 of file pgmstrings\&.h\&.
.SS "#define \fBHIBYTE\fP(\fBx\fP)   ((char*)(&(\fBx\fP)))[1]"
.PP
Definition at line 5 of file pgmstrings\&.h\&.
.SS "#define \fBLOBYTE\fP(\fBx\fP)   ((char*)(&(\fBx\fP)))[0]"
.PP
Definition at line 4 of file pgmstrings\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const char Unk_Contents_str [] \fBPROGMEM\fP = '\\r\\nRequest error\&. Error code:\\t'"
.PP
Definition at line 10 of file pgmstrings\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
