.TH "Included Libraries/USB_Host_Shield_2.0-master/PS4USB.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/PS4USB.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'hiduniversal\&.h'\fP
.br
\fC#include 'PS4Parser\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPS4USB\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPS4_VID\fP   0x054C"
.br
.ti -1c
.RI "#define \fBPS4_PID\fP   0x05C4"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPS4USB\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBPS4_PID\fP   0x05C4"
.PP
Definition at line 25 of file PS4USB\&.h\&.
.SS "#define \fBPS4_VID\fP   0x054C"
.PP
Definition at line 24 of file PS4USB\&.h\&.
.SH "Variable Documentation"
.PP 
.SS " \fBPS4USB\fP  \fB__attribute__\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
