.TH "Included Libraries/USB_Host_Shield_2.0-master/Wii.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/Wii.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Wii\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t WII_LEDS[] \fBPROGMEM\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint32_t WII_PROCONTROLLER_BUTTONS [] \fBPROGMEM\fP"\fBInitial value:\fP
.PP
.nf
 {
        0x00, 
        0x10, 
        0x20, 
        0x40, 
        0x80, 

        0x90, 
        0xA0, 
        0xC0, 
        0xD0, 
        0xE0, 
        0xF0, 
}
.fi
.PP
Definition at line 25 of file Wii\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
