.TH "BASICCDB" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASICCDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <masstorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBOpcode\fP"
.br
.ti -1c
.RI "unsigned \fBunused\fP: 5"
.br
.ti -1c
.RI "unsigned \fBLUN\fP: 3"
.br
.ti -1c
.RI "uint8_t \fBinfo\fP [12]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 185 of file masstorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBBASICCDB::info\fP[12]"
.PP
Definition at line 191 of file masstorage\&.h\&.
.SS "unsigned \fBBASICCDB::LUN\fP"
.PP
Definition at line 189 of file masstorage\&.h\&.
.SS "uint8_t \fBBASICCDB::Opcode\fP"
.PP
Definition at line 186 of file masstorage\&.h\&.
.SS "unsigned \fBBASICCDB::unused\fP"
.PP
Definition at line 188 of file masstorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
