.TH "Capacity" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Capacity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <masstorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBdata\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 179 of file masstorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBCapacity::data\fP[8]"
.PP
Definition at line 180 of file masstorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
