.TH "Included Libraries/USB_Host_Shield_2.0-master/cdcprolific.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/cdcprolific.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cdcacm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPL2303\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPL_VID\fP   0x067B"
.br
.ti -1c
.RI "#define \fBPL_PID\fP   ( 0x2303 || 0x0609 )"
.br
.ti -1c
.RI "#define \fBPROLIFIC_REV_H\fP   0x0202"
.br
.ti -1c
.RI "#define \fBPROLIFIC_REV_X\fP   0x0300"
.br
.ti -1c
.RI "#define \fBPROLIFIC_REV_HX_CHIP_D\fP   0x0400"
.br
.ti -1c
.RI "#define \fBPROLIFIC_REV_1\fP   0x0001"
.br
.ti -1c
.RI "#define \fBkXOnChar\fP   '\\x11'"
.br
.ti -1c
.RI "#define \fBkXOffChar\fP   '\\x13'"
.br
.ti -1c
.RI "#define \fBSPECIAL_SHIFT\fP   (5)"
.br
.ti -1c
.RI "#define \fBSPECIAL_MASK\fP   ((1<<\fBSPECIAL_SHIFT\fP) - 1)"
.br
.ti -1c
.RI "#define \fBSTATE_ALL\fP   ( PD_RS232_S_MASK | PD_S_MASK )"
.br
.ti -1c
.RI "#define \fBFLOW_RX_AUTO\fP   ( PD_RS232_A_RFR | PD_RS232_A_DTR | PD_RS232_A_RXO )"
.br
.ti -1c
.RI "#define \fBFLOW_TX_AUTO\fP   ( PD_RS232_A_CTS | PD_RS232_A_DSR | PD_RS232_A_TXO | PD_RS232_A_DCD )"
.br
.ti -1c
.RI "#define \fBCAN_BE_AUTO\fP   ( \fBFLOW_RX_AUTO\fP | \fBFLOW_TX_AUTO\fP )"
.br
.ti -1c
.RI "#define \fBCAN_NOTIFY\fP   ( PD_RS232_N_MASK )"
.br
.ti -1c
.RI "#define \fBEXTERNAL_MASK\fP   ( PD_S_MASK | (PD_RS232_S_MASK & ~PD_RS232_S_LOOP) )"
.br
.ti -1c
.RI "#define \fBINTERNAL_DELAY\fP   ( PD_RS232_S_LOOP )"
.br
.ti -1c
.RI "#define \fBDEFAULT_AUTO\fP   ( PD_RS232_A_DTR | PD_RS232_A_RFR | PD_RS232_A_CTS | PD_RS232_A_DSR )"
.br
.ti -1c
.RI "#define \fBDEFAULT_NOTIFY\fP   0x00"
.br
.ti -1c
.RI "#define \fBDEFAULT_STATE\fP   ( PD_S_TX_ENABLE | PD_S_RX_ENABLE | PD_RS232_A_TXO | PD_RS232_A_RXO )"
.br
.ti -1c
.RI "#define \fBCONTINUE_SEND\fP   1"
.br
.ti -1c
.RI "#define \fBPAUSE_SEND\fP   2"
.br
.ti -1c
.RI "#define \fBkRxAutoFlow\fP   ((UInt32)( PD_RS232_A_RFR | PD_RS232_A_DTR | PD_RS232_A_RXO ))"
.br
.ti -1c
.RI "#define \fBkTxAutoFlow\fP   ((UInt32)( PD_RS232_A_CTS | PD_RS232_A_DSR | PD_RS232_A_TXO | PD_RS232_A_DCD ))"
.br
.ti -1c
.RI "#define \fBkControl_StateMask\fP   ((UInt32)( PD_RS232_S_CTS | PD_RS232_S_DSR | PD_RS232_S_CAR | PD_RS232_S_RI  ))"
.br
.ti -1c
.RI "#define \fBkRxQueueState\fP   ((UInt32)( PD_S_RXQ_EMPTY | PD_S_RXQ_LOW_WATER | PD_S_RXQ_HIGH_WATER | PD_S_RXQ_FULL ))"
.br
.ti -1c
.RI "#define \fBkTxQueueState\fP   ((UInt32)( PD_S_TXQ_EMPTY | PD_S_TXQ_LOW_WATER | PD_S_TXQ_HIGH_WATER | PD_S_TXQ_FULL ))"
.br
.ti -1c
.RI "#define \fBkCONTROL_DTR\fP   0x01"
.br
.ti -1c
.RI "#define \fBkCONTROL_RTS\fP   0x02"
.br
.ti -1c
.RI "#define \fBkStateTransientMask\fP   0x74"
.br
.ti -1c
.RI "#define \fBkBreakError\fP   0x04"
.br
.ti -1c
.RI "#define \fBkFrameError\fP   0x10"
.br
.ti -1c
.RI "#define \fBkParityError\fP   0x20"
.br
.ti -1c
.RI "#define \fBkOverrunError\fP   0x40"
.br
.ti -1c
.RI "#define \fBkCTS\fP   0x80"
.br
.ti -1c
.RI "#define \fBkDSR\fP   0x02"
.br
.ti -1c
.RI "#define \fBkRI\fP   0x08"
.br
.ti -1c
.RI "#define \fBkDCD\fP   0x01"
.br
.ti -1c
.RI "#define \fBkHandshakeInMask\fP   ((UInt32)( PD_RS232_S_CTS | PD_RS232_S_DSR | PD_RS232_S_CAR | PD_RS232_S_RI  ))"
.br
.ti -1c
.RI "#define \fBVENDOR_WRITE_REQUEST_TYPE\fP   0x40"
.br
.ti -1c
.RI "#define \fBVENDOR_WRITE_REQUEST\fP   0x01"
.br
.ti -1c
.RI "#define \fBVENDOR_READ_REQUEST_TYPE\fP   0xc0"
.br
.ti -1c
.RI "#define \fBVENDOR_READ_REQUEST\fP   0x01"
.br
.ti -1c
.RI "#define \fBSET_DCR0\fP   0x00"
.br
.ti -1c
.RI "#define \fBGET_DCR0\fP   0x80"
.br
.ti -1c
.RI "#define \fBDCR0_INIT\fP   0x01"
.br
.ti -1c
.RI "#define \fBDCR0_INIT_H\fP   0x41"
.br
.ti -1c
.RI "#define \fBDCR0_INIT_X\fP   0x61"
.br
.ti -1c
.RI "#define \fBSET_DCR1\fP   0x01"
.br
.ti -1c
.RI "#define \fBGET_DCR1\fP   0x81"
.br
.ti -1c
.RI "#define \fBDCR1_INIT_H\fP   0x80"
.br
.ti -1c
.RI "#define \fBDCR1_INIT_X\fP   0x00"
.br
.ti -1c
.RI "#define \fBSET_DCR2\fP   0x02"
.br
.ti -1c
.RI "#define \fBGET_DCR2\fP   0x82"
.br
.ti -1c
.RI "#define \fBDCR2_INIT_H\fP   0x24"
.br
.ti -1c
.RI "#define \fBDCR2_INIT_X\fP   0x44"
.br
.ti -1c
.RI "#define \fBRESET_DOWNSTREAM_DATA_PIPE\fP   0x08"
.br
.ti -1c
.RI "#define \fBRESET_UPSTREAM_DATA_PIPE\fP   0x09"
.br
.ti -1c
.RI "#define \fBPL_MAX_ENDPOINTS\fP   4"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtXO_State\fP { \fBkXOnSent\fP =  -2, \fBkXOffSent\fP =  -1, \fBkXO_Idle\fP =  0, \fBkXOffNeeded\fP =  1, \fBkXOnNeeded\fP =  2 }"
.br
.ti -1c
.RI "enum \fBpl2303_type\fP { \fBunknown\fP, \fBtype_1\fP, \fBrev_X\fP, \fBrev_HX\fP, \fBrev_H\fP }"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBCAN_BE_AUTO\fP   ( \fBFLOW_RX_AUTO\fP | \fBFLOW_TX_AUTO\fP )"
.PP
Definition at line 40 of file cdcprolific\&.h\&.
.SS "#define \fBCAN_NOTIFY\fP   ( PD_RS232_N_MASK )"
.PP
Definition at line 41 of file cdcprolific\&.h\&.
.SS "#define \fBCONTINUE_SEND\fP   1"
.PP
Definition at line 48 of file cdcprolific\&.h\&.
.SS "#define \fBDCR0_INIT\fP   0x01"
.PP
Definition at line 89 of file cdcprolific\&.h\&.
.SS "#define \fBDCR0_INIT_H\fP   0x41"
.PP
Definition at line 90 of file cdcprolific\&.h\&.
.SS "#define \fBDCR0_INIT_X\fP   0x61"
.PP
Definition at line 91 of file cdcprolific\&.h\&.
.SS "#define \fBDCR1_INIT_H\fP   0x80"
.PP
Definition at line 95 of file cdcprolific\&.h\&.
.SS "#define \fBDCR1_INIT_X\fP   0x00"
.PP
Definition at line 96 of file cdcprolific\&.h\&.
.SS "#define \fBDCR2_INIT_H\fP   0x24"
.PP
Definition at line 100 of file cdcprolific\&.h\&.
.SS "#define \fBDCR2_INIT_X\fP   0x44"
.PP
Definition at line 101 of file cdcprolific\&.h\&.
.SS "#define \fBDEFAULT_AUTO\fP   ( PD_RS232_A_DTR | PD_RS232_A_RFR | PD_RS232_A_CTS | PD_RS232_A_DSR )"
.PP
Definition at line 44 of file cdcprolific\&.h\&.
.SS "#define \fBDEFAULT_NOTIFY\fP   0x00"
.PP
Definition at line 45 of file cdcprolific\&.h\&.
.SS "#define \fBDEFAULT_STATE\fP   ( PD_S_TX_ENABLE | PD_S_RX_ENABLE | PD_RS232_A_TXO | PD_RS232_A_RXO )"
.PP
Definition at line 46 of file cdcprolific\&.h\&.
.SS "#define \fBEXTERNAL_MASK\fP   ( PD_S_MASK | (PD_RS232_S_MASK & ~PD_RS232_S_LOOP) )"
.PP
Definition at line 42 of file cdcprolific\&.h\&.
.SS "#define \fBFLOW_RX_AUTO\fP   ( PD_RS232_A_RFR | PD_RS232_A_DTR | PD_RS232_A_RXO )"
.PP
Definition at line 38 of file cdcprolific\&.h\&.
.SS "#define \fBFLOW_TX_AUTO\fP   ( PD_RS232_A_CTS | PD_RS232_A_DSR | PD_RS232_A_TXO | PD_RS232_A_DCD )"
.PP
Definition at line 39 of file cdcprolific\&.h\&.
.SS "#define \fBGET_DCR0\fP   0x80"
.PP
Definition at line 88 of file cdcprolific\&.h\&.
.SS "#define \fBGET_DCR1\fP   0x81"
.PP
Definition at line 94 of file cdcprolific\&.h\&.
.SS "#define \fBGET_DCR2\fP   0x82"
.PP
Definition at line 99 of file cdcprolific\&.h\&.
.SS "#define \fBINTERNAL_DELAY\fP   ( PD_RS232_S_LOOP )"
.PP
Definition at line 43 of file cdcprolific\&.h\&.
.SS "#define \fBkBreakError\fP   0x04"
.PP
Definition at line 69 of file cdcprolific\&.h\&.
.SS "#define \fBkCONTROL_DTR\fP   0x01"
.PP
Definition at line 57 of file cdcprolific\&.h\&.
.SS "#define \fBkCONTROL_RTS\fP   0x02"
.PP
Definition at line 58 of file cdcprolific\&.h\&.
.SS "#define \fBkControl_StateMask\fP   ((UInt32)( PD_RS232_S_CTS | PD_RS232_S_DSR | PD_RS232_S_CAR | PD_RS232_S_RI  ))"
.PP
Definition at line 53 of file cdcprolific\&.h\&.
.SS "#define \fBkCTS\fP   0x80"
.PP
Definition at line 74 of file cdcprolific\&.h\&.
.SS "#define \fBkDCD\fP   0x01"
.PP
Definition at line 77 of file cdcprolific\&.h\&.
.SS "#define \fBkDSR\fP   0x02"
.PP
Definition at line 75 of file cdcprolific\&.h\&.
.SS "#define \fBkFrameError\fP   0x10"
.PP
Definition at line 70 of file cdcprolific\&.h\&.
.SS "#define \fBkHandshakeInMask\fP   ((UInt32)( PD_RS232_S_CTS | PD_RS232_S_DSR | PD_RS232_S_CAR | PD_RS232_S_RI  ))"
.PP
Definition at line 78 of file cdcprolific\&.h\&.
.SS "#define \fBkOverrunError\fP   0x40"
.PP
Definition at line 72 of file cdcprolific\&.h\&.
.SS "#define \fBkParityError\fP   0x20"
.PP
Definition at line 71 of file cdcprolific\&.h\&.
.SS "#define \fBkRI\fP   0x08"
.PP
Definition at line 76 of file cdcprolific\&.h\&.
.SS "#define \fBkRxAutoFlow\fP   ((UInt32)( PD_RS232_A_RFR | PD_RS232_A_DTR | PD_RS232_A_RXO ))"
.PP
Definition at line 51 of file cdcprolific\&.h\&.
.SS "#define \fBkRxQueueState\fP   ((UInt32)( PD_S_RXQ_EMPTY | PD_S_RXQ_LOW_WATER | PD_S_RXQ_HIGH_WATER | PD_S_RXQ_FULL ))"
.PP
Definition at line 54 of file cdcprolific\&.h\&.
.SS "#define \fBkStateTransientMask\fP   0x74"
.PP
Definition at line 68 of file cdcprolific\&.h\&.
.SS "#define \fBkTxAutoFlow\fP   ((UInt32)( PD_RS232_A_CTS | PD_RS232_A_DSR | PD_RS232_A_TXO | PD_RS232_A_DCD ))"
.PP
Definition at line 52 of file cdcprolific\&.h\&.
.SS "#define \fBkTxQueueState\fP   ((UInt32)( PD_S_TXQ_EMPTY | PD_S_TXQ_LOW_WATER | PD_S_TXQ_HIGH_WATER | PD_S_TXQ_FULL ))"
.PP
Definition at line 55 of file cdcprolific\&.h\&.
.SS "#define \fBkXOffChar\fP   '\\x13'"
.PP
Definition at line 33 of file cdcprolific\&.h\&.
.SS "#define \fBkXOnChar\fP   '\\x11'"
.PP
Definition at line 32 of file cdcprolific\&.h\&.
.SS "#define \fBPAUSE_SEND\fP   2"
.PP
Definition at line 49 of file cdcprolific\&.h\&.
.SS "#define \fBPL_MAX_ENDPOINTS\fP   4"
.PP
Definition at line 116 of file cdcprolific\&.h\&.
.SS "#define \fBPL_PID\fP   ( 0x2303 || 0x0609 )"
.PP
Definition at line 23 of file cdcprolific\&.h\&.
.SS "#define \fBPL_VID\fP   0x067B"
.PP
Definition at line 22 of file cdcprolific\&.h\&.
.SS "#define \fBPROLIFIC_REV_1\fP   0x0001"
.PP
Definition at line 30 of file cdcprolific\&.h\&.
.SS "#define \fBPROLIFIC_REV_H\fP   0x0202"
.PP
Definition at line 27 of file cdcprolific\&.h\&.
.SS "#define \fBPROLIFIC_REV_HX_CHIP_D\fP   0x0400"
.PP
Definition at line 29 of file cdcprolific\&.h\&.
.SS "#define \fBPROLIFIC_REV_X\fP   0x0300"
.PP
Definition at line 28 of file cdcprolific\&.h\&.
.SS "#define \fBRESET_DOWNSTREAM_DATA_PIPE\fP   0x08"
.PP
Definition at line 104 of file cdcprolific\&.h\&.
.SS "#define \fBRESET_UPSTREAM_DATA_PIPE\fP   0x09"
.PP
Definition at line 105 of file cdcprolific\&.h\&.
.SS "#define \fBSET_DCR0\fP   0x00"
.PP
Definition at line 87 of file cdcprolific\&.h\&.
.SS "#define \fBSET_DCR1\fP   0x01"
.PP
Definition at line 93 of file cdcprolific\&.h\&.
.SS "#define \fBSET_DCR2\fP   0x02"
.PP
Definition at line 98 of file cdcprolific\&.h\&.
.SS "#define \fBSPECIAL_MASK\fP   ((1<<\fBSPECIAL_SHIFT\fP) - 1)"
.PP
Definition at line 36 of file cdcprolific\&.h\&.
.SS "#define \fBSPECIAL_SHIFT\fP   (5)"
.PP
Definition at line 35 of file cdcprolific\&.h\&.
.SS "#define \fBSTATE_ALL\fP   ( PD_RS232_S_MASK | PD_S_MASK )"
.PP
Definition at line 37 of file cdcprolific\&.h\&.
.SS "#define \fBVENDOR_READ_REQUEST\fP   0x01"
.PP
Definition at line 84 of file cdcprolific\&.h\&.
.SS "#define \fBVENDOR_READ_REQUEST_TYPE\fP   0xc0"
.PP
Definition at line 83 of file cdcprolific\&.h\&.
.SS "#define \fBVENDOR_WRITE_REQUEST\fP   0x01"
.PP
Definition at line 81 of file cdcprolific\&.h\&.
.SS "#define \fBVENDOR_WRITE_REQUEST_TYPE\fP   0x40"
.PP
Definition at line 80 of file cdcprolific\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBpl2303_type\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIunknown \fP\fP
.TP
\fB\fItype_1 \fP\fP
.TP
\fB\fIrev_X \fP\fP
.TP
\fB\fIrev_HX \fP\fP
.TP
\fB\fIrev_H \fP\fP

.PP
Definition at line 107 of file cdcprolific\&.h\&.
.SS "enum \fBtXO_State\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIkXOnSent \fP\fP
.TP
\fB\fIkXOffSent \fP\fP
.TP
\fB\fIkXO_Idle \fP\fP
.TP
\fB\fIkXOffNeeded \fP\fP
.TP
\fB\fIkXOnNeeded \fP\fP

.PP
Definition at line 60 of file cdcprolific\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
