.TH "GHID_Dallas_1_Wire" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID_Dallas_1_Wire \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GHID_Dallas_1_Wire\&.h>\fP
.PP
Inherits \fBOneWire\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbuffer_struct_t\fP * \fBread_bulk\fP (byte length)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbuffer_struct_t\fP \fBbuffer\fP"
.br
.RI "\fIPublic Context\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class is an extended class of the Dallas \fBOneWire\fP class\&. It provides a more comprehensive methodology for the user to implement this type of device\&.
.PP
\fBSee also:\fP
.RS 4
\fBOneWire\&.h\fP 
.RE
.PP

.PP
Definition at line 30 of file GHID_Dallas_1_Wire\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbuffer_struct_t\fP * \fBGHID_Dallas_1_Wire::read_bulk\fP (bytelength)"This is the read bulk method\&. We give it a length and, this method handles the reading of the one wire bus\&.
.PP
\fBParameters:\fP
.RS 4
\fIlength\fP - byte 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBbuffer_struct_t\fP - buffer struct 
.RE
.PP
Read for length times
.PP
returns the pointer to the class internal buffer struct 
.PP
Definition at line 10 of file GHID_Dallas_1_Wire\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbuffer_struct_t\fP \fBGHID_Dallas_1_Wire::buffer\fP"
.PP
Public Context\&. Frankly there is nothing to be implemented in this api in which is not touched on in the API added to the includes folder\&. Publicly accessible buffer struct 
.PP
Definition at line 42 of file GHID_Dallas_1_Wire\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
