.TH "Included Libraries/USB_Host_Shield_2.0-master/hidescriptorparser.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/hidescriptorparser.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'hidescriptorparser\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const 
.br
\fBReportDescParserBase::usagePageTitles0\fP[] \fBPROGMEM\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* const \fBReportDescParserBase::medInstrTitles4\fP [] \fBPROGMEM\fP"\fBInitial value:\fP
.PP
.nf
 {
        pstrUsagePageGenericDesktopControls,
        pstrUsagePageSimulationControls,
        pstrUsagePageVRControls,
        pstrUsagePageSportControls,
        pstrUsagePageGameControls,
        pstrUsagePageGenericDeviceControls,
        pstrUsagePageKeyboardKeypad,
        pstrUsagePageLEDs,
        pstrUsagePageButton,
        pstrUsagePageOrdinal,
        pstrUsagePageTelephone,
        pstrUsagePageConsumer,
        pstrUsagePageDigitizer,
        pstrUsagePagePID,
        pstrUsagePageUnicode
}
.fi
.PP
Definition at line 20 of file hidescriptorparser\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
