.TH "KBDINFO" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KBDINFO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hidboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBbmLeftCtrl\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmLeftShift\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmLeftAlt\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmLeftGUI\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmRightCtrl\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmRightShift\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmRightAlt\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBbmRightGUI\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "uint8_t \fBbReserved\fP"
.br
.ti -1c
.RI "uint8_t \fBKeys\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file hidboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. } "
.SS "uint8_t \fBKBDINFO::bmLeftAlt\fP"
.PP
Definition at line 101 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bmLeftCtrl\fP"
.PP
Definition at line 99 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bmLeftGUI\fP"
.PP
Definition at line 102 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bmLeftShift\fP"
.PP
Definition at line 100 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bmRightAlt\fP"
.PP
Definition at line 105 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bmRightCtrl\fP"
.PP
Definition at line 103 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bmRightGUI\fP"
.PP
Definition at line 106 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bmRightShift\fP"
.PP
Definition at line 104 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::bReserved\fP"
.PP
Definition at line 108 of file hidboot\&.h\&.
.SS "uint8_t \fBKBDINFO::Keys\fP[6]"
.PP
Definition at line 109 of file hidboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
