.TH "PL2303" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PL2303 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cdcprolific\&.h>\fP
.PP
Inherits \fBACM\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPL2303\fP (USB *pusb, \fBCDCAsyncOper\fP *pasync)"
.br
.ti -1c
.RI "virtual uint8_t \fBInit\fP (uint8_t parent, uint8_t port, bool lowspeed)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file cdcprolific\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPL2303::PL2303\fP (USB *pusb, \fBCDCAsyncOper\fP *pasync)"
.PP
Definition at line 19 of file cdcprolific\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint8_t \fBPL2303::Init\fP (uint8_tparent, uint8_tport, boollowspeed)\fC [virtual]\fP"
.PP
Reimplemented from \fBACM\fP\&.
.PP
Definition at line 24 of file cdcprolific\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
