.TH "ReportDescParser2" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReportDescParser2 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hidescriptorparser\&.h>\fP
.PP
Inherits \fBReportDescParserBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReportDescParser2\fP (uint16_t len, uint8_t *pbuf)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual uint8_t \fBParseItem\fP (uint8_t **pp, uint16_t *pcntdn)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 147 of file hidescriptorparser\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBReportDescParser2::ReportDescParser2\fP (uint16_tlen, uint8_t *pbuf)\fC [inline]\fP"
.PP
Definition at line 163 of file hidescriptorparser\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "uint8_t \fBReportDescParser2::ParseItem\fP (uint8_t **pp, uint16_t *pcntdn)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBReportDescParserBase\fP\&.
.PP
Definition at line 1440 of file hidescriptorparser\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
