.TH "UniversalReportParser" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniversalReportParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hidescriptorparser\&.h>\fP
.PP
Inherits \fBHIDReportParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBParse\fP (\fBHID\fP *hid, bool is_rpt_id, uint8_t len, uint8_t *buf)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 168 of file hidescriptorparser\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBUniversalReportParser::Parse\fP (\fBHID\fP *hid, boolis_rpt_id, uint8_tlen, uint8_t *buf)\fC [virtual]\fP"
.PP
Implements \fBHIDReportParser\fP\&.
.PP
Definition at line 1592 of file hidescriptorparser\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
