.TH "Included Libraries/USB_Host_Shield_2.0-master/XBOXOLD.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/XBOXOLD.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br
\fC#include 'controllerEnums\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXBOXOLD\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEP_MAXPKTSIZE\fP   32"
.br
.ti -1c
.RI "#define \fBEP_INTERRUPT\fP   0x03"
.br
.ti -1c
.RI "#define \fBXBOX_CONTROL_PIPE\fP   0"
.br
.ti -1c
.RI "#define \fBXBOX_INPUT_PIPE\fP   1"
.br
.ti -1c
.RI "#define \fBXBOX_OUTPUT_PIPE\fP   2"
.br
.ti -1c
.RI "#define \fBXBOX_VID\fP   0x045E"
.br
.ti -1c
.RI "#define \fBMADCATZ_VID\fP   0x1BAD"
.br
.ti -1c
.RI "#define \fBJOYTECH_VID\fP   0x162E"
.br
.ti -1c
.RI "#define \fBXBOX_OLD_PID1\fP   0x0202"
.br
.ti -1c
.RI "#define \fBXBOX_OLD_PID2\fP   0x0285"
.br
.ti -1c
.RI "#define \fBXBOX_OLD_PID3\fP   0x0287"
.br
.ti -1c
.RI "#define \fBXBOX_OLD_PID4\fP   0x0289"
.br
.ti -1c
.RI "#define \fBbmREQ_HID_OUT\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.br
.ti -1c
.RI "#define \fBHID_REQUEST_SET_REPORT\fP   0x09"
.br
.ti -1c
.RI "#define \fBXBOX_MAX_ENDPOINTS\fP   3"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBbmREQ_HID_OUT\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.PP
Definition at line 46 of file XBOXOLD\&.h\&.
.SS "#define \fBEP_INTERRUPT\fP   0x03"
.PP
Definition at line 28 of file XBOXOLD\&.h\&.
.SS "#define \fBEP_MAXPKTSIZE\fP   32"
.PP
Definition at line 25 of file XBOXOLD\&.h\&.
.SS "#define \fBHID_REQUEST_SET_REPORT\fP   0x09"
.PP
Definition at line 47 of file XBOXOLD\&.h\&.
.SS "#define \fBJOYTECH_VID\fP   0x162E"
.PP
Definition at line 38 of file XBOXOLD\&.h\&.
.SS "#define \fBMADCATZ_VID\fP   0x1BAD"
.PP
Definition at line 37 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_CONTROL_PIPE\fP   0"
.PP
Definition at line 31 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_INPUT_PIPE\fP   1"
.PP
Definition at line 32 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_MAX_ENDPOINTS\fP   3"
.PP
Definition at line 49 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_OLD_PID1\fP   0x0202"
.PP
Definition at line 40 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_OLD_PID2\fP   0x0285"
.PP
Definition at line 41 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_OLD_PID3\fP   0x0287"
.PP
Definition at line 42 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_OLD_PID4\fP   0x0289"
.PP
Definition at line 43 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_OUTPUT_PIPE\fP   2"
.PP
Definition at line 33 of file XBOXOLD\&.h\&.
.SS "#define \fBXBOX_VID\fP   0x045E"
.PP
Definition at line 36 of file XBOXOLD\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
