.TH "Included Libraries/USB_Host_Shield_2.0-master/XBOXOLD.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/XBOXOLD.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'XBOXOLD\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t XBOXOLD_BUTTONS[] \fBPROGMEM\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t XBOXOLD_BUTTONS [] \fBPROGMEM\fP"\fBInitial value:\fP
.PP
.nf
 {
        0x01, 
        0x08, 
        0x02, 
        0x04, 

        0x20, 
        0x10, 
        0x40, 
        0x80, 

        
        4, 
        5, 
        6, 
        7, 

        1, 
        0, 
        2, 
        3, 
}
.fi
Buttons on the controllers 
.PP
Definition at line 24 of file XBOXOLD\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
