.TH "Included Libraries/USB_Host_Shield_2.0-master/cdcacm.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/cdcacm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCALL_MGMNT_FUNC_DESCR\fP"
.br
.ti -1c
.RI "struct \fBACM_FUNC_DESCR\fP"
.br
.ti -1c
.RI "struct \fBTEL_RINGER_FUNC_DESCR\fP"
.br
.ti -1c
.RI "struct \fBLINE_CODING\fP"
.br
.ti -1c
.RI "struct \fBCLASS_NOTIFICATION\fP"
.br
.ti -1c
.RI "class \fBCDCAsyncOper\fP"
.br
.ti -1c
.RI "class \fBACM\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBbmREQ_CDCOUT\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.br
.ti -1c
.RI "#define \fBbmREQ_CDCIN\fP   USB_SETUP_DEVICE_TO_HOST|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_DLCM\fP   0x01"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_ACM\fP   0x02"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_TCM\fP   0x03"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_MCCM\fP   0x04"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_CAPI\fP   0x05"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_ETHERNET\fP   0x06"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_ATM\fP   0x07"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_WIRELESS_HANDSET\fP   0x08"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_DEVICE_MANAGEMENT\fP   0x09"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_MOBILE_DIRECT_LINE\fP   0x0A"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_OBEX\fP   0x0B"
.br
.ti -1c
.RI "#define \fBCDC_SUBCLASS_ETHERNET_EMU\fP   0x0C"
.br
.ti -1c
.RI "#define \fBCDC_PROTOCOL_ITU_T_V_250\fP   0x01"
.br
.ti -1c
.RI "#define \fBCDC_PROTOCOL_PCCA_101\fP   0x02"
.br
.ti -1c
.RI "#define \fBCDC_PROTOCOL_PCCA_101_O\fP   0x03"
.br
.ti -1c
.RI "#define \fBCDC_PROTOCOL_GSM_7_07\fP   0x04"
.br
.ti -1c
.RI "#define \fBCDC_PROTOCOL_3GPP_27_07\fP   0x05"
.br
.ti -1c
.RI "#define \fBCDC_PROTOCOL_C_S0017_0\fP   0x06"
.br
.ti -1c
.RI "#define \fBCDC_PROTOCOL_USB_EEM\fP   0x07"
.br
.ti -1c
.RI "#define \fBCDC_SEND_ENCAPSULATED_COMMAND\fP   0x00"
.br
.ti -1c
.RI "#define \fBCDC_GET_ENCAPSULATED_RESPONSE\fP   0x01"
.br
.ti -1c
.RI "#define \fBCDC_SET_COMM_FEATURE\fP   0x02"
.br
.ti -1c
.RI "#define \fBCDC_GET_COMM_FEATURE\fP   0x03"
.br
.ti -1c
.RI "#define \fBCDC_CLEAR_COMM_FEATURE\fP   0x04"
.br
.ti -1c
.RI "#define \fBCDC_SET_AUX_LINE_STATE\fP   0x10"
.br
.ti -1c
.RI "#define \fBCDC_SET_HOOK_STATE\fP   0x11"
.br
.ti -1c
.RI "#define \fBCDC_PULSE_SETUP\fP   0x12"
.br
.ti -1c
.RI "#define \fBCDC_SEND_PULSE\fP   0x13"
.br
.ti -1c
.RI "#define \fBCDC_SET_PULSE_TIME\fP   0x14"
.br
.ti -1c
.RI "#define \fBCDC_RING_AUX_JACK\fP   0x15"
.br
.ti -1c
.RI "#define \fBCDC_SET_LINE_CODING\fP   0x20"
.br
.ti -1c
.RI "#define \fBCDC_GET_LINE_CODING\fP   0x21"
.br
.ti -1c
.RI "#define \fBCDC_SET_CONTROL_LINE_STATE\fP   0x22"
.br
.ti -1c
.RI "#define \fBCDC_SEND_BREAK\fP   0x23"
.br
.ti -1c
.RI "#define \fBCDC_SET_RINGER_PARMS\fP   0x30"
.br
.ti -1c
.RI "#define \fBCDC_GET_RINGER_PARMS\fP   0x31"
.br
.ti -1c
.RI "#define \fBCDC_SET_OPERATION_PARMS\fP   0x32"
.br
.ti -1c
.RI "#define \fBCDC_GET_OPERATION_PARMS\fP   0x33"
.br
.ti -1c
.RI "#define \fBCDC_SET_LINE_PARMS\fP   0x34"
.br
.ti -1c
.RI "#define \fBCDC_GET_LINE_PARMS\fP   0x35"
.br
.ti -1c
.RI "#define \fBCDC_DIAL_DIGITS\fP   0x36"
.br
.ti -1c
.RI "#define \fBNETWORK_CONNECTION\fP   0x00"
.br
.ti -1c
.RI "#define \fBRESPONSE_AVAILABLE\fP   0x01"
.br
.ti -1c
.RI "#define \fBAUX_JACK_HOOK_STATE\fP   0x08"
.br
.ti -1c
.RI "#define \fBRING_DETECT\fP   0x09"
.br
.ti -1c
.RI "#define \fBSERIAL_STATE\fP   0x20"
.br
.ti -1c
.RI "#define \fBCALL_STATE_CHANGE\fP   0x28"
.br
.ti -1c
.RI "#define \fBLINE_STATE_CHANGE\fP   0x29"
.br
.ti -1c
.RI "#define \fBCONNECTION_SPEED_CHANGE\fP   0x2a"
.br
.ti -1c
.RI "#define \fBACM_MAX_ENDPOINTS\fP   4"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBACM_FUNC_DESCR\fP \fBDLM_FUNC_DESCR\fP"
.br
.ti -1c
.RI "typedef struct \fBACM_FUNC_DESCR\fP \fBTEL_OPER_MODES_FUNC_DESCR\fP"
.br
.ti -1c
.RI "typedef struct \fBACM_FUNC_DESCR\fP \fBTEL_CALL_STATE_REP_CPBL_FUNC_DESCR\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBACM_MAX_ENDPOINTS\fP   4"
.PP
Definition at line 136 of file cdcacm\&.h\&.
.SS "#define \fBAUX_JACK_HOOK_STATE\fP   0x08"
.PP
Definition at line 77 of file cdcacm\&.h\&.
.SS "#define \fBbmREQ_CDCIN\fP   USB_SETUP_DEVICE_TO_HOST|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.PP
Definition at line 23 of file cdcacm\&.h\&.
.SS "#define \fBbmREQ_CDCOUT\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.PP
Definition at line 22 of file cdcacm\&.h\&.
.SS "#define \fBCALL_STATE_CHANGE\fP   0x28"
.PP
Definition at line 80 of file cdcacm\&.h\&.
.SS "#define \fBCDC_CLEAR_COMM_FEATURE\fP   0x04"
.PP
Definition at line 55 of file cdcacm\&.h\&.
.SS "#define \fBCDC_DIAL_DIGITS\fP   0x36"
.PP
Definition at line 72 of file cdcacm\&.h\&.
.SS "#define \fBCDC_GET_COMM_FEATURE\fP   0x03"
.PP
Definition at line 54 of file cdcacm\&.h\&.
.SS "#define \fBCDC_GET_ENCAPSULATED_RESPONSE\fP   0x01"
.PP
Definition at line 50 of file cdcacm\&.h\&.
.SS "#define \fBCDC_GET_LINE_CODING\fP   0x21"
.PP
Definition at line 63 of file cdcacm\&.h\&.
.SS "#define \fBCDC_GET_LINE_PARMS\fP   0x35"
.PP
Definition at line 71 of file cdcacm\&.h\&.
.SS "#define \fBCDC_GET_OPERATION_PARMS\fP   0x33"
.PP
Definition at line 69 of file cdcacm\&.h\&.
.SS "#define \fBCDC_GET_RINGER_PARMS\fP   0x31"
.PP
Definition at line 67 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PROTOCOL_3GPP_27_07\fP   0x05"
.PP
Definition at line 44 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PROTOCOL_C_S0017_0\fP   0x06"
.PP
Definition at line 45 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PROTOCOL_GSM_7_07\fP   0x04"
.PP
Definition at line 43 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PROTOCOL_ITU_T_V_250\fP   0x01"
.PP
Definition at line 40 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PROTOCOL_PCCA_101\fP   0x02"
.PP
Definition at line 41 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PROTOCOL_PCCA_101_O\fP   0x03"
.PP
Definition at line 42 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PROTOCOL_USB_EEM\fP   0x07"
.PP
Definition at line 46 of file cdcacm\&.h\&.
.SS "#define \fBCDC_PULSE_SETUP\fP   0x12"
.PP
Definition at line 58 of file cdcacm\&.h\&.
.SS "#define \fBCDC_RING_AUX_JACK\fP   0x15"
.PP
Definition at line 61 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SEND_BREAK\fP   0x23"
.PP
Definition at line 65 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SEND_ENCAPSULATED_COMMAND\fP   0x00"
.PP
Definition at line 49 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SEND_PULSE\fP   0x13"
.PP
Definition at line 59 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_AUX_LINE_STATE\fP   0x10"
.PP
Definition at line 56 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_COMM_FEATURE\fP   0x02"
.PP
Definition at line 53 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_CONTROL_LINE_STATE\fP   0x22"
.PP
Definition at line 64 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_HOOK_STATE\fP   0x11"
.PP
Definition at line 57 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_LINE_CODING\fP   0x20"
.PP
Definition at line 62 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_LINE_PARMS\fP   0x34"
.PP
Definition at line 70 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_OPERATION_PARMS\fP   0x32"
.PP
Definition at line 68 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_PULSE_TIME\fP   0x14"
.PP
Definition at line 60 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SET_RINGER_PARMS\fP   0x30"
.PP
Definition at line 66 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_ACM\fP   0x02"
.PP
Definition at line 27 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_ATM\fP   0x07"
.PP
Definition at line 32 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_CAPI\fP   0x05"
.PP
Definition at line 30 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_DEVICE_MANAGEMENT\fP   0x09"
.PP
Definition at line 34 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_DLCM\fP   0x01"
.PP
Definition at line 26 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_ETHERNET\fP   0x06"
.PP
Definition at line 31 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_ETHERNET_EMU\fP   0x0C"
.PP
Definition at line 37 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_MCCM\fP   0x04"
.PP
Definition at line 29 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_MOBILE_DIRECT_LINE\fP   0x0A"
.PP
Definition at line 35 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_OBEX\fP   0x0B"
.PP
Definition at line 36 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_TCM\fP   0x03"
.PP
Definition at line 28 of file cdcacm\&.h\&.
.SS "#define \fBCDC_SUBCLASS_WIRELESS_HANDSET\fP   0x08"
.PP
Definition at line 33 of file cdcacm\&.h\&.
.SS "#define \fBCONNECTION_SPEED_CHANGE\fP   0x2a"
.PP
Definition at line 82 of file cdcacm\&.h\&.
.SS "#define \fBLINE_STATE_CHANGE\fP   0x29"
.PP
Definition at line 81 of file cdcacm\&.h\&.
.SS "#define \fBNETWORK_CONNECTION\fP   0x00"
.PP
Definition at line 75 of file cdcacm\&.h\&.
.SS "#define \fBRESPONSE_AVAILABLE\fP   0x01"
.PP
Definition at line 76 of file cdcacm\&.h\&.
.SS "#define \fBRING_DETECT\fP   0x09"
.PP
Definition at line 78 of file cdcacm\&.h\&.
.SS "#define \fBSERIAL_STATE\fP   0x20"
.PP
Definition at line 79 of file cdcacm\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef  struct \fBACM_FUNC_DESCR\fP  \fBDLM_FUNC_DESCR\fP"
.SS "typedef  struct \fBACM_FUNC_DESCR\fP
 \fBTEL_CALL_STATE_REP_CPBL_FUNC_DESCR\fP"
.SS "typedef  struct \fBACM_FUNC_DESCR\fP  \fBTEL_OPER_MODES_FUNC_DESCR\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
