.TH "GHID API/GHID_SPI.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID API/GHID_SPI.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SPI\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbuffer_struct_t\fP"
.br
.RI "\fIBuffer structure\&. \fP"
.ti -1c
.RI "struct \fBspi_settings_t\fP"
.br
.RI "\fISPI device settings\&. \fP"
.ti -1c
.RI "class \fBGHID_SPI\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMOSI\fP   51"
.br
.RI "\fIThese are hardware definitions for the SPI interface \\\&. \fP"
.ti -1c
.RI "#define \fBMISO\fP   51"
.br
.ti -1c
.RI "#define \fBSCLK\fP   52"
.br
.ti -1c
.RI "#define \fBSS\fP   53"
.br
.ti -1c
.RI "#define \fBMAX_BUFFER\fP   255"
.br
.RI "\fIMax buffer size\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBspi_device_address_map_t\fP { \fBSTART_DEVICE_ENUM\fP, \fBDEFAULT_DEVICE\fP =  0, \fBEND_DEVICE_ENUM\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBbuffer_struct_t\fP \fBspi_buffer\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMAX_BUFFER\fP   255"
.PP
Max buffer size\&. 
.PP
Definition at line 22 of file GHID_SPI\&.h\&.
.SS "#define \fBMISO\fP   51"
.PP
Definition at line 17 of file GHID_SPI\&.h\&.
.SS "#define \fBMOSI\fP   51"
.PP
These are hardware definitions for the SPI interface \\\&. 
.PP
Definition at line 16 of file GHID_SPI\&.h\&.
.SS "#define \fBSCLK\fP   52"
.PP
Definition at line 18 of file GHID_SPI\&.h\&.
.SS "#define \fBSS\fP   53"
.PP
Definition at line 19 of file GHID_SPI\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBspi_device_address_map_t\fP"This is a spi network device list\&. You must implement this map with the appropriate pin allocations so that SS can select propertly\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISTART_DEVICE_ENUM \fP\fP
.TP
\fB\fIDEFAULT_DEVICE \fP\fP
.TP
\fB\fIEND_DEVICE_ENUM \fP\fP

.PP
Definition at line 34 of file GHID_SPI\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBbuffer_struct_t\fP \fBspi_buffer\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
