.TH "GHID API/GHID_Digital_Port.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GHID API/GHID_Digital_Port.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDigital_Port\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
