.TH "Included Libraries/USB_Host_Shield_2.0-master/PS3USB.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/PS3USB.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Usb\&.h'\fP
.br
\fC#include 'PS3Enums\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPS3USB\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEP_MAXPKTSIZE\fP   64"
.br
.ti -1c
.RI "#define \fBEP_INTERRUPT\fP   0x03"
.br
.ti -1c
.RI "#define \fBPS3_CONTROL_PIPE\fP   0"
.br
.ti -1c
.RI "#define \fBPS3_OUTPUT_PIPE\fP   1"
.br
.ti -1c
.RI "#define \fBPS3_INPUT_PIPE\fP   2"
.br
.ti -1c
.RI "#define \fBPS3_VID\fP   0x054C"
.br
.ti -1c
.RI "#define \fBPS3_PID\fP   0x0268"
.br
.ti -1c
.RI "#define \fBPS3NAVIGATION_PID\fP   0x042F"
.br
.ti -1c
.RI "#define \fBPS3MOVE_PID\fP   0x03D5"
.br
.ti -1c
.RI "#define \fBbmREQ_HID_OUT\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.br
.ti -1c
.RI "#define \fBbmREQ_HID_IN\fP   USB_SETUP_DEVICE_TO_HOST|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.br
.ti -1c
.RI "#define \fBHID_REQUEST_GET_REPORT\fP   0x01"
.br
.ti -1c
.RI "#define \fBHID_REQUEST_SET_REPORT\fP   0x09"
.br
.ti -1c
.RI "#define \fBPS3_MAX_ENDPOINTS\fP   3"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBbmREQ_HID_IN\fP   USB_SETUP_DEVICE_TO_HOST|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.PP
Definition at line 43 of file PS3USB\&.h\&.
.SS "#define \fBbmREQ_HID_OUT\fP   USB_SETUP_HOST_TO_DEVICE|USB_SETUP_TYPE_CLASS|USB_SETUP_RECIPIENT_INTERFACE"
.PP
Definition at line 42 of file PS3USB\&.h\&.
.SS "#define \fBEP_INTERRUPT\fP   0x03"
.PP
Definition at line 28 of file PS3USB\&.h\&.
.SS "#define \fBEP_MAXPKTSIZE\fP   64"
.PP
Definition at line 25 of file PS3USB\&.h\&.
.SS "#define \fBHID_REQUEST_GET_REPORT\fP   0x01"
.PP
Definition at line 45 of file PS3USB\&.h\&.
.SS "#define \fBHID_REQUEST_SET_REPORT\fP   0x09"
.PP
Definition at line 46 of file PS3USB\&.h\&.
.SS "#define \fBPS3_CONTROL_PIPE\fP   0"
.PP
Definition at line 31 of file PS3USB\&.h\&.
.SS "#define \fBPS3_INPUT_PIPE\fP   2"
.PP
Definition at line 33 of file PS3USB\&.h\&.
.SS "#define \fBPS3_MAX_ENDPOINTS\fP   3"
.PP
Definition at line 48 of file PS3USB\&.h\&.
.SS "#define \fBPS3_OUTPUT_PIPE\fP   1"
.PP
Definition at line 32 of file PS3USB\&.h\&.
.SS "#define \fBPS3_PID\fP   0x0268"
.PP
Definition at line 37 of file PS3USB\&.h\&.
.SS "#define \fBPS3_VID\fP   0x054C"
.PP
Definition at line 36 of file PS3USB\&.h\&.
.SS "#define \fBPS3MOVE_PID\fP   0x03D5"
.PP
Definition at line 39 of file PS3USB\&.h\&.
.SS "#define \fBPS3NAVIGATION_PID\fP   0x042F"
.PP
Definition at line 38 of file PS3USB\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
