.TH "PS4Data" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS4Data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PS4Parser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBhatValue\fP [4]"
.br
.ti -1c
.RI "\fBPS4Buttons\fP \fBbtn\fP"
.br
.ti -1c
.RI "uint8_t \fBtrigger\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBdummy\fP [3]"
.br
.ti -1c
.RI "int16_t \fBgyroY\fP"
.br
.ti -1c
.RI "int16_t \fBgyroZ\fP"
.br
.ti -1c
.RI "int16_t \fBgyroX\fP"
.br
.ti -1c
.RI "int16_t \fBaccX\fP"
.br
.ti -1c
.RI "int16_t \fBaccZ\fP"
.br
.ti -1c
.RI "int16_t \fBaccY\fP"
.br
.ti -1c
.RI "uint8_t \fBdummy2\fP [9]"
.br
.ti -1c
.RI "\fBtouchpadXY\fP \fBxy\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 84 of file PS4Parser\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t \fBPS4Data::accX\fP"
.PP
Definition at line 93 of file PS4Parser\&.h\&.
.SS "int16_t \fBPS4Data::accY\fP"
.PP
Definition at line 93 of file PS4Parser\&.h\&.
.SS "int16_t \fBPS4Data::accZ\fP"
.PP
Definition at line 93 of file PS4Parser\&.h\&.
.SS "\fBPS4Buttons\fP \fBPS4Data::btn\fP"
.PP
Definition at line 87 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Data::dummy\fP[3]"
.PP
Definition at line 91 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Data::dummy2\fP[9]"
.PP
Definition at line 96 of file PS4Parser\&.h\&.
.SS "int16_t \fBPS4Data::gyroX\fP"
.PP
Definition at line 92 of file PS4Parser\&.h\&.
.SS "int16_t \fBPS4Data::gyroY\fP"
.PP
Definition at line 92 of file PS4Parser\&.h\&.
.SS "int16_t \fBPS4Data::gyroZ\fP"
.PP
Definition at line 92 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Data::hatValue\fP[4]"
.PP
Definition at line 86 of file PS4Parser\&.h\&.
.SS "uint8_t \fBPS4Data::trigger\fP[2]"
.PP
Definition at line 88 of file PS4Parser\&.h\&.
.SS "\fBtouchpadXY\fP \fBPS4Data::xy\fP[3]"
.PP
Definition at line 97 of file PS4Parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
