.TH "Included Libraries/SoftwareSerial.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/SoftwareSerial.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br
\fC#include <Stream\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoftwareSerial\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_SS_MAX_RX_BUFF\fP   64"
.br
.ti -1c
.RI "#define \fBGCC_VERSION\fP   (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fB_SS_MAX_RX_BUFF\fP   64"
.PP
Definition at line 42 of file SoftwareSerial\&.h\&.
.SS "#define \fBGCC_VERSION\fP   (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)"
.PP
Definition at line 44 of file SoftwareSerial\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
