.TH "Included Libraries/SPI.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/SPI.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br
\fC#include <avr/pgmspace\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSPIClass\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSPI_CLOCK_DIV4\fP   0x00"
.br
.ti -1c
.RI "#define \fBSPI_CLOCK_DIV16\fP   0x01"
.br
.ti -1c
.RI "#define \fBSPI_CLOCK_DIV64\fP   0x02"
.br
.ti -1c
.RI "#define \fBSPI_CLOCK_DIV128\fP   0x03"
.br
.ti -1c
.RI "#define \fBSPI_CLOCK_DIV2\fP   0x04"
.br
.ti -1c
.RI "#define \fBSPI_CLOCK_DIV8\fP   0x05"
.br
.ti -1c
.RI "#define \fBSPI_CLOCK_DIV32\fP   0x06"
.br
.ti -1c
.RI "#define \fBSPI_MODE0\fP   0x00"
.br
.ti -1c
.RI "#define \fBSPI_MODE1\fP   0x04"
.br
.ti -1c
.RI "#define \fBSPI_MODE2\fP   0x08"
.br
.ti -1c
.RI "#define \fBSPI_MODE3\fP   0x0C"
.br
.ti -1c
.RI "#define \fBSPI_MODE_MASK\fP   0x0C"
.br
.ti -1c
.RI "#define \fBSPI_CLOCK_MASK\fP   0x03"
.br
.ti -1c
.RI "#define \fBSPI_2XCLOCK_MASK\fP   0x01"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSPIClass\fP \fBSPI\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBSPI_2XCLOCK_MASK\fP   0x01"
.PP
Definition at line 34 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_DIV128\fP   0x03"
.PP
Definition at line 21 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_DIV16\fP   0x01"
.PP
Definition at line 19 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_DIV2\fP   0x04"
.PP
Definition at line 22 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_DIV32\fP   0x06"
.PP
Definition at line 24 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_DIV4\fP   0x00"
.PP
Definition at line 18 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_DIV64\fP   0x02"
.PP
Definition at line 20 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_DIV8\fP   0x05"
.PP
Definition at line 23 of file SPI\&.h\&.
.SS "#define \fBSPI_CLOCK_MASK\fP   0x03"
.PP
Definition at line 33 of file SPI\&.h\&.
.SS "#define \fBSPI_MODE0\fP   0x00"
.PP
Definition at line 27 of file SPI\&.h\&.
.SS "#define \fBSPI_MODE1\fP   0x04"
.PP
Definition at line 28 of file SPI\&.h\&.
.SS "#define \fBSPI_MODE2\fP   0x08"
.PP
Definition at line 29 of file SPI\&.h\&.
.SS "#define \fBSPI_MODE3\fP   0x0C"
.PP
Definition at line 30 of file SPI\&.h\&.
.SS "#define \fBSPI_MODE_MASK\fP   0x0C"
.PP
Definition at line 32 of file SPI\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBSPIClass\fP \fBSPI\fP"
.PP
Definition at line 14 of file SPI\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
