.TH "Included Libraries/USB_Host_Shield_2.0-master/SPP.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/SPP.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BTD\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSPP\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSDP_SERVICE_SEARCH_ATTRIBUTE_REQUEST_PDU\fP   0x06"
.br
.ti -1c
.RI "#define \fBSDP_SERVICE_SEARCH_ATTRIBUTE_RESPONSE_PDU\fP   0x07"
.br
.ti -1c
.RI "#define \fBSERIALPORT_UUID\fP   0x1101"
.br
.ti -1c
.RI "#define \fBL2CAP_UUID\fP   0x0100"
.br
.ti -1c
.RI "#define \fBRFCOMM_SABM\fP   0x2F"
.br
.ti -1c
.RI "#define \fBRFCOMM_UA\fP   0x63"
.br
.ti -1c
.RI "#define \fBRFCOMM_UIH\fP   0xEF"
.br
.ti -1c
.RI "#define \fBRFCOMM_DISC\fP   0x43"
.br
.ti -1c
.RI "#define \fBextendAddress\fP   0x01"
.br
.ti -1c
.RI "#define \fBBT_RFCOMM_PN_CMD\fP   0x83"
.br
.ti -1c
.RI "#define \fBBT_RFCOMM_PN_RSP\fP   0x81"
.br
.ti -1c
.RI "#define \fBBT_RFCOMM_MSC_CMD\fP   0xE3"
.br
.ti -1c
.RI "#define \fBBT_RFCOMM_MSC_RSP\fP   0xE1"
.br
.ti -1c
.RI "#define \fBBT_RFCOMM_RPN_CMD\fP   0x93"
.br
.ti -1c
.RI "#define \fBBT_RFCOMM_RPN_RSP\fP   0x91"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBT_RFCOMM_MSC_CMD\fP   0xE3"
.PP
Definition at line 41 of file SPP\&.h\&.
.SS "#define \fBBT_RFCOMM_MSC_RSP\fP   0xE1"
.PP
Definition at line 42 of file SPP\&.h\&.
.SS "#define \fBBT_RFCOMM_PN_CMD\fP   0x83"
.PP
Definition at line 39 of file SPP\&.h\&.
.SS "#define \fBBT_RFCOMM_PN_RSP\fP   0x81"
.PP
Definition at line 40 of file SPP\&.h\&.
.SS "#define \fBBT_RFCOMM_RPN_CMD\fP   0x93"
.PP
Definition at line 43 of file SPP\&.h\&.
.SS "#define \fBBT_RFCOMM_RPN_RSP\fP   0x91"
.PP
Definition at line 44 of file SPP\&.h\&.
.SS "#define \fBextendAddress\fP   0x01"
.PP
Definition at line 36 of file SPP\&.h\&.
.SS "#define \fBL2CAP_UUID\fP   0x0100"
.PP
Definition at line 27 of file SPP\&.h\&.
.SS "#define \fBRFCOMM_DISC\fP   0x43"
.PP
Definition at line 34 of file SPP\&.h\&.
.SS "#define \fBRFCOMM_SABM\fP   0x2F"
.PP
Definition at line 30 of file SPP\&.h\&.
.SS "#define \fBRFCOMM_UA\fP   0x63"
.PP
Definition at line 31 of file SPP\&.h\&.
.SS "#define \fBRFCOMM_UIH\fP   0xEF"
.PP
Definition at line 32 of file SPP\&.h\&.
.SS "#define \fBSDP_SERVICE_SEARCH_ATTRIBUTE_REQUEST_PDU\fP   0x06"
.PP
Definition at line 24 of file SPP\&.h\&.
.SS "#define \fBSDP_SERVICE_SEARCH_ATTRIBUTE_RESPONSE_PDU\fP   0x07"
.PP
Definition at line 25 of file SPP\&.h\&.
.SS "#define \fBSERIALPORT_UUID\fP   0x1101"
.PP
Definition at line 26 of file SPP\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
