.TH "Included Libraries/USB_Host_Shield_2.0-master/usbhub.cpp" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/usbhub.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'usbhub\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPrintHubPortStatus\fP (\fBUSBHub\fP *hubptr, uint8_t addr, uint8_t port, bool print_changes)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBPrintHubPortStatus\fP (\fBUSBHub\fP *hubptr, uint8_taddr, uint8_tport, boolprint_changes)"
.PP
Definition at line 376 of file usbhub\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
