.TH "Included Libraries/USB_Host_Shield_2.0-master/xboxEnums.h" 3 "Sun Mar 30 2014" "Version version 2.0" "GHID Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Included Libraries/USB_Host_Shield_2.0-master/xboxEnums.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'controllerEnums\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLEDModeEnum\fP { \fBROTATING\fP =  0x0A, \fBFASTBLINK\fP =  0x0B, \fBSLOWBLINK\fP =  0x0C, \fBALTERNATING\fP =  0x0D }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t XBOX_LEDS[] \fBPROGMEM\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLEDModeEnum\fP"Enum used to set special LED modes supported by the Xbox controller\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIROTATING \fP\fP
.TP
\fB\fIFASTBLINK \fP\fP
.TP
\fB\fISLOWBLINK \fP\fP
.TP
\fB\fIALTERNATING \fP\fP

.PP
Definition at line 24 of file xboxEnums\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const uint16_t XBOX_BUTTONS [] \fBPROGMEM\fP"\fBInitial value:\fP
.PP
.nf
 {
        0x00, 
        0x02, 
        0x03, 
        0x04, 
        0x05, 
        0x01, 
}
.fi
Used to set the LEDs on the controllers
.PP
Buttons on the controllers 
.PP
Definition at line 32 of file xboxEnums\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GHID Framework from the source code\&.
